### ISSUE TITLE
Alerts and alert.SetAuthenticationCredentials

### ISSUE THREAD

**Issue by LeszekJC** [atata-framework/atata#1]
Hello, I had a problem. I must log in to application by Windows authebtication. Typical browser alert, and I don't find solution for that in Atata. 

In selenium, in that case I use:

```
WebDriverWait wait = new WebDriverWait(_webdriver, new TimeSpan(0, 0, 10));
            IAlert alert = wait.Until(ExpectedConditions.AlertIsPresent());
            alert.SetAuthenticationCredentials("login", "somePAss");
            alert.Accept();
```

So I try use driver used in ATATA in that style

```
 WebDriverWait wait = new WebDriverWait(AtataContext.Current.Driver, new TimeSpan(0, 0, 10));
            IAlert alert = wait.Until(ExpectedConditions.AlertIsPresent());
            alert.SetAuthenticationCredentials("login", "somePAss");
            alert.Accept();
```

But this don't work. The page for myUlr is not open. 

The full set up for solution:

```[SetUp]
        public void Initialize()
        {
            AtataContext.Build().
            UseChrome().
                UseBaseUrl("myUlr ").
                UseNUnitTestName().
                LogNUnitError().
                SetUp();
            WebDriverWait wait = new WebDriverWait(AtataContext.Current.Driver, new TimeSpan(0, 0, 10));
            IAlert alert = wait.Until(ExpectedConditions.AlertIsPresent());
            alert.SetAuthenticationCredentials("login", "somePAss");
            alert.Accept();
        }

**Comment by YevgeniyShunevych** [comment]
Hi, thanks for question.

Before you try to fill credentials form you need to perform initial Go operation to open the page in browser. SetUp() call just configures the environment and start browser without any page navigation.

        public void Initialize()
        {
            AtataContext.Build().
            UseChrome().
                UseBaseUrl("myUlr ").
                UseNUnitTestName().
                LogNUnitError().
                SetUp();

            Go.To<HomePage>(); // Or pass another page object class.

            WebDriverWait wait = new WebDriverWait(AtataContext.Current.Driver, new TimeSpan(0, 0, 10));
            IAlert alert = wait.Until(ExpectedConditions.AlertIsPresent());
            alert.SetAuthenticationCredentials("login", "somePAss");
            alert.Accept();
        }

But any way credentials popup/alert cannot be found in Chrome (latest version) for me, when it is really present in the browser. Exception is thrown upon wait.Until(...), even using clean WebDriver without Atata.

There is another way to pass Windows credentials. Please try to specify the windows credentials in your base URL, e.g.:
`UseBaseUrl("http://USERNAME:PASSWORD@someurl.com")`
