### ISSUE TITLE
Culture configuration

### ISSUE THREAD

**Issue by YevgeniyShunevych** [atata-framework/atata#103]
Add support of culture configuration.

- Add property to `AtataContext` and `AtataBuildingContext`:
   ```cs
   public CultureInfo Culture { get; }
   ```

- Add methods to `AtataContextBuilder` to specify culture:
   ```cs
   public AtataContextBuilder UseCulture(CultureInfo culture);

   public AtataContextBuilder UseCulture(string cultureName);
   ```

## Usage

```cs
AtataContext.Configure().
    UseCulture("en-us")
```

**Comment by DimaDubyk** [comment]
Thanks a lot for this feature, it is very easy to test app for different locales.
