### ISSUE TITLE
[Question] About Email Inputs

### ISSUE THREAD

**Issue by BRS999** [atata-framework/atata#104]
Hello,

First of all thanks for creating this framework!

Question about email inputs. I noticed that the framework doesn't include support for some inputs like email. 

I ended up creating a property as such:

```
        [ControlDefinition("input[@type='email']")]
        [FindById("some_id")]
        public Input<string,_> Email { get; private set; }
```

I'm curious, is there a reason this type of input was excluded?

Thanks again!

**Comment by YevgeniyShunevych** [comment]
Hi Ben,

You know, I just missed some input types. With HTML5 there is a lot of them: https://www.w3schools.com/tags/att_input_type.asp. I will try to add extra controls for inputs within the next Atata release. Maybe some other HTML elements that are missing as controls?

Also you can skip `[ControlDefinition("input[@type='email']")]` in the case when you do accurate control search, like by ID. Just:

```cs
[FindById("some_id")]
public Input<string,_> Email { get; private set; }
```

`Input<T, TOwner>` will find element with email type as it has such `[ControlDefinition("input[@type!='button' and @type!='submit' and @type!='reset']")]`.
