### ISSUE TITLE
[Question] About Phantomjs

### ISSUE THREAD

**Issue by BRS999** [atata-framework/atata#105]
Hello,

I want to use Phantomjs to run some automated tests. I notice that when a test fails I get a small screenshot. Is there a way to maximize the viewport or take a screenshot of the entire view via Phantomjs?

Thanks!

**Comment by YevgeniyShunevych** [comment]
Hi,

Yes, for PhantomJS it works the same way as for other browsers. After `AtataContext` is set up, you can invoke:
```cs
AtataContext.Current.Driver.Manage().Window.Maximize();
```

**Comment by BRS999** [comment]
That works. Thanks again!

**Comment by YevgeniyShunevych** [comment]
Welcome. By the way, to set specific size you can use:
```cs
AtataContext.Current.Driver.Manage().Window.Size = new Size(1200, 1000);
```
