### ISSUE TITLE
Atata tests are very slow under netcoreapp2.0 target framework (.Net Core 2.0)

### ISSUE THREAD

**Issue by DimaDubyk** [atata-framework/atata#106]
When I am trying to run tests for xUnitTestProject (.Net Core) with target framework netcoreapp2.0 tests are very slow. But when I switch to net47 target framework tests run with normal speed.
There is some delay (~ 10 seconds) before accessing elements.

**Comment by YevgeniyShunevych** [comment]
Hi,

Please read "WebDriver .NET Core Issues" section in [Atata 0.15.0 Released](https://atata-framework.github.io/blog/2017/10/12/atata-0.15.0-released/). There is configuration method `WithFixOfCommandExecutionDelay` that fixes this WebDriver issue.

**Comment by DimaDubyk** [comment]
Thanks a lot!
