### ISSUE TITLE
[Question] About Tables

### ISSUE THREAD

**Issue by BRS999** [atata-framework/atata#107]
Hello again!

I want to target the second table in a page.  Because I'm using a plugin they both have almost the same class names.  Is there a way I can do that?

Thanks in advance.

**Comment by YevgeniyShunevych** [comment]
Hello,

You can use `[FindByClass("some-class", Index = 1)]` to find the second one. Every `FindAttribute` class has `Index` property.

Or just use `[FindByIndex(1)]` to find a second table on the page without filtering by class.

**Comment by BRS999** [comment]
Works perfectly. Thanks again.
