### ISSUE TITLE
Does Atata framework supports to take full screenshot?

### ISSUE THREAD

**Issue by SivaATF** [atata-framework/atata#108]
I have some issue with taking a full page screenshot. Currently it takes only viewport area.

**Comment by YevgeniyShunevych** [comment]
Atata as well as WebDriver doesn't have built-in functionality for full page screenshots, just viewport. You can check https://automatetheplanet.com/full-page-screenshots-webdriver-html2canvas/ for custom implementation using html2canvas.js.

Any way, I will think on implementation of such functionality in Atata for one of the future releases.

**Comment by SivaATF** [comment]
I will look into the html2canvas.js implementation. Thanks.
