### ISSUE TITLE
Question: Can we check if opened tab/window is PDF and check PDF content?

### ISSUE THREAD

**Issue by SivaATF** [atata-framework/atata#109]
I'm trying to print a page and on click PDF opens in a new window. Now i need to do two things.

1. Check if the opened file is PDF
2. Check the PDF content is present.

As far i have understood the Atata framework there is no extension available. Any help on this?

Thanks

**Comment by YevgeniyShunevych** [comment]
It is not an obvious task, but quite interesting. You will have to use some extra package to read PDF file, like [Spire.PDF](https://www.nuget.org/packages/Spire.PDF/). But first, extract URL to the file, download file, then read text from it with some PDF library and finally verify the text content.

I can try to create some tutorial. But I need to find free time for that.

**Comment by SivaATF** [comment]
Thank you.
