### ISSUE TITLE
Question: Can we perform if else, switch case using Should extension

### ISSUE THREAD

**Issue by SivaATF** [atata-framework/atata#110]
Hello,

I'm trying to achieve if else condition check with Should like extension. (i.e. if an control is visible, then check for a text or control value else check for grid count.

controlPage.If.Not.NoContent.Exists().Then().Nocontent.Should.Equal("some text")

Currently i can do like below
if(controlPage.NoContent.Exists()){
....}
else{
...}
Thanks.

**Comment by YevgeniyShunevych** [comment]
Hello,

You can use `Do` method of `PageObject`:

```cs
Go.To<SomePage>().
    Do(x =>
    {
        if (x.NoContent.Exists(SearchOptions.SafelyAtOnce()))
            x.NoContent.Should.Equal("some text");
        else
            x.Grid.Rows.Should.HaveCount(0);
    });
```

Or even simpler:

```cs
Go.To<SomePage>().
    Do(x => x.NoContent.Exists(SearchOptions.SafelyAtOnce())
        ? x.NoContent.Should.Equal("some text")
        : x.Grid.Rows.Should.HaveCount(0));
```

**Comment by SivaATF** [comment]
This should work. Thank you.
