### ISSUE TITLE
Question: Want to check if Atata framework has any support for CSV/Excel datasource

### ISSUE THREAD

**Issue by SivaATF** [atata-framework/atata#111]
I'm trying to test with different type of data using CSV/Excel. Would be nice if the framework has any support for it.

Thanks.

**Comment by YevgeniyShunevych** [comment]
Actually, data sources are related to test engines, like NUnit and XUnit. There are built-in abstract functionality there to add external data sources.

However, please check new `AtataSamples.CsvDataSource.sln` solution in [atata-framework/atata-samples](https://github.com/atata-framework/atata-samples) repository. The solution uses CSV as data source for NUnit test cases. I created 2 sets of test cases there, with and without expected results. The solution uses [CsvHelper](https://www.nuget.org/packages/CsvHelper/) package for CSV reading. For Excel it should be something in similar way.

**Comment by SivaATF** [comment]
Awesome!! Will take a look thank you.

**Comment by YevgeniyShunevych** [comment]
Welcome.
