### ISSUE TITLE
Back to the previous iframe

### ISSUE THREAD

**Issue by elzbietafuchs** [atata-framework/atata#13]
Hi!
I have a little problem. How can I switch to the previous i frame?
to Switch to other iframe i used your examle (it's below).
When I finsh working on New iframe i click Link and automatically my New iFrame is closed. 
To switch on New iframe i used SomeButton.**ClickAndGo**(), but now i Clicked Link and I can't use ClickAndGo().

Ela! :)

**Page object as iframe**

An example of page object for page that is located inside the other one as iframe:
using Atata;
using OpenQA.Selenium;
using _ = SampleApp.SomePage;

namespace SampleApp
{
    public class SomePage : Page<_>
    {
        protected override void OnInit()
        {
            base.OnInit();

            IWebElement iframe = Driver.Get(By.XPath(".//iframe[@id='some-id']"));
            Driver.SwitchTo().Frame(iframe);
        }

        protected override void CleanUp()
        {
            base.CleanUp();

            Driver.SwitchTo().DefaultContent();
        }
    }
}

**Comment by YevgeniyShunevych** [comment]
Hi Ela,

Could you please describe your test case with more details? The work with iframes is tricky and I also would like to enhance this functionality in Atata.

So you have a main page that contains iframe that loads another page. And when you click on the link of the iframe's page, another page is loaded in the same iframe. Then you want to switch to this new iframe's page and work with it. Do I understand correctly?

**Comment by elzbietafuchs** [comment]
OK :)

Well, i have main page, on this page is ButtonA ,
after clik on this button new iframe is opened.
Now i'm working with the new iframe.
I finish working with click on Link 'Save Record', which automatically close new iframe.
Now i see main page.

So...
ButtonA.ClickAndGo().  ----- I'm going to new iframe 
......               --------------- I'm  working with new iframe
LinkSaveRecord.Click().     ------------- My new iframe is closed after this click


If SaveRecord element was Button I would use ClickAndGo() to go back to my main page, but it's Link :(
--------------------------------------------
public class MainPage : Page <_> 
{
[FindByXpath("...")]
public Button<NewIframe,_> ButtonA {get; private set;}
}

public class NewIframe : Page<_>
{ 
[FindByXpath("...")]
public Link <_> LinkSaveRecord {get; private set;}
}

**Comment by YevgeniyShunevych** [comment]
I see. In your case case `LinkSaveRecord` should be of type `Link<MainPage, _>`. And use it like `LinkSaveRecord.ClickAndGo()`. And you will get back to `MainPage`.

If you invoke `Driver.SwitchTo().DefaultContent();` in `NewIframe` `CleanUp` method it should be OK. WebDriver will switch to primary/main page when you do `LinkSaveRecord.ClickAndGo()` and you can continue to work with `MainPage`.

```cs
public class NewIframe : Page<_>
{
    [FindByXPath("...")]
    public Link<MainPage, _> LinkSaveRecord { get; private set; }

    protected override void OnInit()
    {
        base.OnInit();

        IWebElement iframe = Driver.Get(By.XPath(".//iframe[@id='some-id']"));
        Driver.SwitchTo().Frame(iframe);
    }

    protected override void CleanUp()
    {
        base.CleanUp();

        try
        {
            Driver.SwitchTo().DefaultContent();
        }
        catch // Temporary try/catch fix. Exception can be occurred during AtataContext clean-up. It will be fixed in 0.12.0 version of Atata.
        {
        }
    }
}
```
Please reply if it does not work.

**Comment by elzbietafuchs** [comment]
Thanks a lot! :)

**Comment by YevgeniyShunevych** [comment]
Welcome. :) Glad that helped.
