### ISSUE TITLE
enhancement: Any kind of automatic Page object generator with Atata controls?

### ISSUE THREAD

**Issue by SivaATF** [atata-framework/atata#138]
I know this is not currently available, but just want to check if there is anything planned on having a automatic page object generator with Atata controls (with FindBy attributes etc)

**Comment by YevgeniyShunevych** [comment]
I thought about this. But it is quite complex task that requires a lot of time to spend on it. Besides I have a long list of features and enhancements to add to Atata itself. So I cannot say whether generator will be some day, definitely not in the nearest future.

I also think to add a list of C# snippets to [Atata Templates](https://marketplace.visualstudio.com/items?itemName=YevgeniyShunevych.AtataTemplates) VS extension.
