### ISSUE TITLE
How to avoid navigating to a page if I have defined the URL for the page object

### ISSUE THREAD

**Issue by encius** [atata-framework/atata#141]
How can I avoid navigating to a page if I have defined the URL for the page object?

Something like: On<SignInPage>.

**Comment by YevgeniyShunevych** [comment]
If I understood correctly then to avoid navigating (URL change) during `Go.To` is:

```cs
Go.To<SomePage>(navigate: false)
```

**Comment by encius** [comment]
Thanks! Didn't see any example, but I saw it now in the code :) Will look better next time!
