### ISSUE TITLE
How to proceed with links under <span> HTML elements?

### ISSUE THREAD

**Issue by valipopa** [atata-framework/atata#142]
Hi there,

I am facing an issue where I need to click a link which is represented like this: 

`<span onmouseover="ShowElement(this.id,'tt21','Show','')" onmouseout="ShowElement(this.id,'tt21','Hide','')" class="hyperlink" id="project_Row1">some text</span>`

Cannot do this with Link, as it is span. Tried with Content, Field or Clickable, but not able to click it. Any advice will be much appreciated it.

Thanks.

**Comment by YevgeniyShunevych** [comment]
Basically, `Clickable<TOwner>` should work for most cases:

```cs
using Atata;
using _ = SampleApp.SamplePage;

namespace SampleApp
{
    public class SamplePage : Page<_>
    {
        [FindById("project_Row1")]
        public Clickable<_> SomeLink { get; private set; }
    }
}
```

But I see `onmouseover` on `<span>`. What element does it show on hover? Maybe you need to execute `Hover()` for this span and then click some other element that will be shown.
