### ISSUE TITLE
How to Switch to New Window

### ISSUE THREAD

**Issue by freetorn2002** [atata-framework/atata#143]
Hi,
I am new to Atata framework.I already started using this fantastic framework.I have a question.
when i click link in my webpage,it opens a new window.It is not a pop up window.How to switch to the new window ?please send me your comments.
Thanks

**Comment by YevgeniyShunevych** [comment]
Hi. You can use `Go.ToNextWindow<TPageObject>()` method. For example:

```cs
Go.To<SomePage>().
    // Do some actions.
    ButtonThatOpensWindow.Click();

Go.ToNextWindow<SomeOtherPage>(). // Switches to newly opened window.
    // Do some actions in scope of new window.
    CloseWindow(); // Closes window and switches back to the previous window.

Go.To<SomePage>(navigate: false)...
   // Continue to work within the first window.
```

There is also `Go.ToWindow<TPageObject>(...)` method, which takes the name of the window and can be used for more specific switching between windows if you have more than 2 of them opened at the same time.
