### ISSUE TITLE
Atata Core template's project on first launch. System.MissingMethodException: 'No parameterless constructor or constructor without non-optional parameters defined for the 

### ISSUE THREAD

**Issue by rpokrovskij** [atata-framework/atata#158]
Atata templates were installed (VS 2017), Core project created.
Test created.
chromedriver 2.9.248315 placed to the recommended place "bin\Debug\netcoreapp2.0"
tested mvc app launched with dotnet run (ver 2.1.100)

Test lounched. 
Expected behavior: test executed successfully OR **meaningful error message**.

In reality exception thrown (chrome browser opened): 
System.MissingMethodException: 'No parameterless constructor or constructor without non-optional parameters defined for the 
Atata.OptionList`2[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],
[AdminkaV1.Injected.AspCore.MvcApp.Automation.NETCore.Test.CreateRolePage, 
AdminkaV1.Injected.AspCore.MvcApp.Automation.NETCore.Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] type.'

Test content: 

```
    [TestFixture]
    public class RolesAutomatedTest
    {
        [SetUp]
        public void SetUp()
        {
            // Find information about AtataContext set-up on https://atata-framework.github.io/getting-started/#set-up.
            AtataContext.Configure().
                UseChrome().
                    WithFixOfCommandExecutionDelay().
                    WithLocalDriverPath().
                UseBaseUrl("http://localhost:63558").
                Build();
        }

        [TearDown]
        public void TearDown()
        {
            AtataContext.Current.CleanUp();
        }

        [Test]
        public void SignIn()
        {
            Go.To<CreateRolePage>()
                .RoleName.Set("TestIsland99").Create.Click();
        }
    }
```

Chrome:

![image](https://user-images.githubusercontent.com/11598038/37599286-0c6642b2-2b8d-11e8-91f1-02144cf033ea.png)

Test: 

```
namespace AdminkaV1.Injected.AspCore.MvcApp.Automation.NETCore.Test
{
   [Url("Roles/Create")]
   [VerifyTitle]
   [VerifyH1]
   public class CreateRolePage : Page<CreateRolePage>
   {
       public TextInput<CreateRolePage> RoleName { get; private set; }

       public OptionList<string, CreateRolePage> Privileges { get; private set;}
       public OptionList<int, CreateRolePage> Groups { get; private set; }

       public Button<CreateRolePage> Create { get; private set; }
   }
}
```

**Comment by YevgeniyShunevych** [comment]
The problem is in `OptionList` properties of `CreateRolePage`.

```cs
public OptionList<string, CreateRolePage> Privileges { get; private set;}
public OptionList<int, CreateRolePage> Groups { get; private set; }
```

`OptionList` is the base abstract class for `RadioButtonList` and `CheckBoxList`. It cannot be used directly. You should use `RadioButtonList`, `CheckBoxList` or some other control instead.

**Comment by YevgeniyShunevych** [comment]
When you perform navigation to a page object, Atata initializes all properties of the page object. It is also possible to mark property with `[IgnoreInit]` attribute to avoid property auto initialization, and maybe initialize it in custom way in overridden `OnInit` or `OnInitCompleted` method.
