### ISSUE TITLE
[Question] Clicking on an "item"

### ISSUE THREAD

**Issue by BRS999** [atata-framework/atata#173]
Hello there!

I'm trying to figure out how to click on an element.

It looks like this.

```
<list>
 <item>
  <span>1</span>
 </item>
 <item>
  <span>2</span>
</list>
```
I can't quite figure out how to click on either item 1 or 2.

Can you point me in the right direction?

Thanks in advance!

**Comment by YevgeniyShunevych** [comment]
Hello,

Please check [ItemsControl](https://atata-framework.github.io/components/#itemscontrol). An example that provided there is similar to your.

**Comment by BRS999** [comment]
That worked. Thanks again!
