### ISSUE TITLE
[Question] Retry Flaky Tests

### ISSUE THREAD

**Issue by BRS999** [atata-framework/atata#174]
Hello again!

I'm running into some flakiness with some of my tests.

I can individually retry some tests but I'm wondering is there a way to set a global retry for tests that fail?

Thanks in advance.

**Comment by YevgeniyShunevych** [comment]
Hello,

If you use Atata with NUnit please take a look at <https://testingrepository.com/retry-failed-tests-in-nunit/>.

**Comment by BRS999** [comment]
Thanks again!
