### ISSUE TITLE
Add PerformActions method to PageObject<TOwner>

### ISSUE THREAD

**Issue by YevgeniyShunevych** [atata-framework/atata#178]
Add method to `PageObject<TOwner>`:

```cs
public TOwner PerformActions(Func<Actions, Actions> actionsBuilder);
```

**Comment by DimaDubyk** [comment]
Hi, do you have any plans about release date of framework with actions support?

**Comment by YevgeniyShunevych** [comment]
Hi. Yes, currently doing the latest changes to the project. v0.17.0 will be released in this week.
