### ISSUE TITLE
NoSQL DB integration

### ISSUE THREAD

**Issue by MonzT** [atata-framework/atata#180]
Hi

Is there a way to integrate with a NoSql DB (like MongoDB)?

**Comment by YevgeniyShunevych** [comment]
Sorry, but specifically for what?

**Comment by YevgeniyShunevych** [comment]
It is a responsibility of testing framework (xUnit, NUnit). For example NUnit has [TestCaseSource attribute](https://github.com/nunit/docs/wiki/TestCaseSource-Attribute) for custom data sources. So for test you can implement custom method that will read the set of test parameters from any source you like (config file, DB, etc). And you need to specify this method as a test case source using an attribute.
