### ISSUE TITLE
TNavigateTo coping with optional pages

### ISSUE THREAD

**Issue by wmolyneux** [atata-framework/atata#181]
I have a 'Login' button defined in a page object
`
[FindByContent("Login")]
public Button<PermissionsPage, LoginPage> Login { get; private set; }
`
Once the user has signed in once they will not get the permissions page again. As I am using the same user each test how can I make the TNavigateTo optional?

My test code looks like:
`
Go.To<LoginPage>()
                .Username.Set("myusername")
                .Password.Set("mypassword")
                .RememberLogin.Set(false)
                .Login.ClickAndGo();
`

**Comment by YevgeniyShunevych** [comment]
If you want to stay on the same page, instead of `ClickAndGo()` do invoke `Click()` method. This way you will stay on the same page.

Maybe I didn't understand you correctly. Please describe a bit your case. What is the other page for next logins? What the test does in permissions page when login for the first time, and where you navigated after permissions page (is next landing page is the same as for other login sessions)?

**Comment by YevgeniyShunevych** [comment]
You can have such field and login method in `UITestFixture` or somewhere else:

```cs
private static readonly List<string> loggedInUsers = new List<string>();

protected LandingPage Login(string userName, string password)
{
    var loginPage = Go.To<LoginPage>().
        Username.Set(userName).
        Password.Set(password).
        RememberLogin.Set(false);

    if (loggedInUsers.Contains(userName)) // Was logged in before and should be navigated to "landing" page.
    {
        retrun loginPage.Login.ClickAndGo<LandingPage>();
    }
    else // First login.
    {
        loggedInUsers.Add(userName);

        retrun loginPage.Login.ClickAndGo<PermissionsPage>().
            DoSomethingThere().
            NavigateToLandingPageButton.ClickAndGo();
    }
}
```

Something like this is also possible.

**Comment by wmolyneux** [comment]
Your example above is very interesting and almost solves my issue. 

Basically when a user presses the 'login' button it may or may not take them to the permissions page before returning them to the homepage of the application as a logged in user.

I cant store an in memory list of 'logged in' users because the tests will just be configured with a user which may or may not have been used in a previous test run. 

Hopefully this makes more sense, thanks for your speedy replies :)

**Comment by YevgeniyShunevych** [comment]
I see. Then you can check what the page is returned after login button is clicked. For example you can rely on page URL or title.

```cs
protected HomePage Login(string userName, string password)
{
    return Go.To<LoginPage>().
        Username.Set(userName).
        Password.Set(password).
        RememberLogin.Set(false).
        Login.Click().
        Do(x => x.PageUrl.Value.EndsWith("/permissions")
            ? Go.To<PermissionsPage>(navigate: false).
                DoSomethingThere().
                NavigateToHomePageButton.ClickAndGo()
            : Go.To<HomePage>(navigate: false));
}
```

**Comment by YevgeniyShunevych** [comment]
And button for such case can be defined without `TNavatageTo` type:

```cs
public Button<LoginPage> Login { get; private set; }
```

**Comment by wmolyneux** [comment]
Thats fantastic! Thank you very much, i'll add this on monday.

**Comment by YevgeniyShunevych** [comment]
Always welcome.
