### ISSUE TITLE
Unable to find element when running in headless mode on linux

### ISSUE THREAD

**Issue by wmolyneux** [atata-framework/atata#182]
I am trying to run my Atata tests on a headless Ubuntu 16.04 VM using 'dotnet build' and 'dotnet test' they execute but Atata fails when running chromedriver in headless mode.

Tests pass on windows in headless mode.

Github page object:
```
using Atata;

namespace TestProject.PageObjects
{
    [Url("/")]
    [VerifyTitle(TermMatch.Equals, "The world’s leading software development platform · GitHub")]
    public class GithubPage : Page<GithubPage>
    {
        [FindByXPath("//a[text()='Sign up']")]
        public Atata.Link<GithubPage> SignUp { get; private set; }
    }
}
```

Test:

```
    [TestClass]
    public class Testing
    {
        private ChromeDriver driver;

        [TestInitialize]
        public void Init()
        {
            var options = new ChromeOptions();
            options.AddArguments("--disable-dev-shm-usage");
            options.AddArguments("headless");
            options.AddArguments("window-size=1920x1080");
            options.AddArguments("--no-sandbox");
            driver = new ChromeDriver("/etc/chrome", options, TimeSpan.FromMinutes(3));
        }

        [TestMethod]
        public void FailsOnLinux_WorksOnWindows()
        {
            AtataContext
                .Configure()
                .UseDriver(() => {
                    return this.driver;
                })
                .UseBaseUrl("https://github.com")
                .Build();

            Go.To<GithubPage>().SignUp.Click();
        }

        [TestMethod]
        public void WorksOnLinuxAndWindows()
        {
            driver.Navigate().GoToUrl("https://github.com");
            driver.FindElementByXPath("//a[text()='Sign up']").Click();
        }

        [TestCleanup]
        public void TestCleanUp()
        {
            this.driver.Dispose();
        }
    }
```

In the above example there are two tests, the Atata one uses the page object model and, when running chromedriver in headless, works on windows but fails on linux.

The second test uses only chromedriver to navigate to the same page and use the same xpath provided in the GithubPage page object. This test passes on both platforms. 

The failure error is:
```
Failed   FailsOnLinux_WorksOnWindows
Error Message:
 Test method TestProject.Tests.Testing.FailsOnLinux_WorksOnWindows threw exception:
Atata.AssertionException: Invalid "Github" page title.
Expected: should equal "The world’s leading software development platform · GitHub"
Actual: ""

Stack Trace:
    at Atata.IDataVerificationProviderExtensions.Satisfy[TData,TOwner](IDataVerificationProvider`2 should, Predicate`1 predicate, String message, TData[] args)
   at Atata.IDataVerificationProviderExtensions.MatchAny[TOwner](IDataVerificationProvider`2 should, TermMatch match, String[] expected)
   at Atata.VerifyTitleAttribute.OnExecute[TOwner](TriggerContext`1 context, String[] values)
   at Atata.UIComponentTriggerSet`1.Execute(TriggerEvents on)
   at Atata.PageObject`1.Init()
   at Atata.Go.To[T](T pageObject, GoOptions options)
   at TestProject.Tests.Testing.FailsOnLinux_WorksOnWindows() in /etc/tests/TestProject/Tests/Testing.cs:line 38
```

What am I doing wrong for getting Atata working in headless mode on linux?

Regards

**Comment by wmolyneux** [comment]
I have also tried running the tests not using the 'headless' chromedriver argument and instead using the linux Xvfb to use a virtual display. 

The selenium test succeeded but the Atata test failed with the error:
```
Failed   FailsOnLinux_WorksOnWindows
Error Message:
 Test method TestProject.Tests.Testing.FailsOnLinux_WorksOnWindows threw exception:
Atata.AssertionException: Invalid "Github" page title.
Expected: should equal "The world’s leading software development platform · GitHub"
Actual: "Index of /"

Stack Trace:
    at Atata.IDataVerificationProviderExtensions.Satisfy[TData,TOwner](IDataVerificationProvider`2 should, Predicate`1 predicate, String message, TData[] args)
   at Atata.IDataVerificationProviderExtensions.MatchAny[TOwner](IDataVerificationProvider`2 should, TermMatch match, String[] expected)
   at Atata.VerifyTitleAttribute.OnExecute[TOwner](TriggerContext`1 context, String[] values)
   at Atata.UIComponentTriggerSet`1.Execute(TriggerEvents on)
   at Atata.PageObject`1.Init()
   at Atata.Go.To[T](T pageObject, GoOptions options)
   at TestProject.Tests.Testing.FailsOnLinux_WorksOnWindows() in /etc/tests/TestProject/Tests/Testing.cs:line 38
```

**Comment by YevgeniyShunevych** [comment]
Hi,

I am try to figure out your issue. But no luck for now.

Anyway could you please do the next thing. Remove `[Url("/")]` attribute from `GithubPage` page object. It is not needed there, and I assume that it can be a reason (strange, but anyway).

**Comment by wmolyneux** [comment]
Weirdly removing the Url has solved the issue. Its strange that the Url attribute works correctly when on windows but when running on linux doesnt work as desired.

**Comment by YevgeniyShunevych** [comment]
I was able to reproduce your issue and figured out why it occurs.

When the navigation to the page object happens thru `Go.To` it gets `Url` attribute of page object and checks is it absolute or relative path:

- If it is relative URL path Atata appends it to `BaseUrl`. Then performs `Driver.Navigate().GoToUrl(uri)`.
- If it is absolute URL path then this URL is used directly without `BaseUrl`.
- If there is no `Url` on page object then just `BaseUrl` is used for navigation.

The check for relative URL happens this way in Atata:

```cs
if (!Uri.TryCreate(url, UriKind.Absolute, out absoluteUri))
{
    //...
}
```

And here comes one of fundamental difference between Linux and Windows. `"/"` or `"/some-path"` - is a relative URI path in Windows, but in Linux - it is an absolute path.

So in your case driver was navigated to "/" URL (without base URL) which was actually handled by browser like "file:///".

This is a bug in Atata and I will fix it in the next version of Atata.

As a temporary workaround you can use one of the following options:

1. Instead of using `Url` attribute, you can do the same by overriding `Navigate` method inside a page object:

```cs
protected override void Navigate()
{
    Go.ToUrl(AtataContext.Current.BaseUrl + "/relative-url");
}
```

2. Add a trailing '/' to `BaseUrl` when configure `AtataContext` like:

```cs
AtataContext.Configure().
    UseBaseUrl("https://github.com/").
```

And on page object you can use `[Url("partial-url")]` without leading `"/"`.

**Comment by wmolyneux** [comment]
Thats very interesting, I assumed it must have been something to do with relative paths when it wasnt working on Linux but was working on Windows.

Thanks for investigating and providing workarounds! 

Glad the issue will be addressed in the future :)
