### ISSUE TITLE
How to execute JavaScript?

### ISSUE THREAD

**Issue by jayeonsu** [atata-framework/atata#183]
I've tried to find a way to execute JavaScript, in the official document, Issues, StackOverflow and google, but I can't still find.

As Selenium supports WebDriver.ExecuteScript, I thought atata also naturally would do.

Is there any way to execute JavaScript by any chance?

**Comment by YevgeniyShunevych** [comment]
Sure, you can get whole instance of `RemoteWebDriver` and invoke any native WebDriver method.

```cs
AtataContext.Current.Driver.ExecuteScript("...");
```

**Comment by jayeonsu** [comment]
Oh! I didn't expect it to be in AtataContext.
Thank you! :)

**Comment by YevgeniyShunevych** [comment]
Always welcome.
