### ISSUE TITLE
IMG Tags

### ISSUE THREAD

**Issue by auriou** [atata-framework/atata#184]
Hello,

I did not find an IMG object for image tags in the Atata namespace. It may be possible to configure a new 
element, for example httml 5 tags. I just miss an example, there may be an inherited class in which we can define a new element with attributes?

Good job, thx

**Comment by auriou** [comment]
Super thanks for your example.

If I may say so, it would not be possible to have this type of writing to retrieve attributes and the binder has a property

```c#
[ControlDefinition("img")]
public class Image<TOwner> : Control<TOwner> where TOwner : PageObject<TOwner>
{
      [BindByAttribute("src")]
      public Text<TOwner> Src { get; private set; }
}
```

Thx

**Comment by YevgeniyShunevych** [comment]
Currently it is possible to implement such data properties this way:

```cs
[ControlDefinition("img")]
public class Image<TOwner> : Control<TOwner>
    where TOwner : PageObject<TOwner>
{
    // Attribute of string type.
    public DataProvider<string, TOwner> Src => Attributes["src"];

    // Attribute of nullable int type.
    // Null will be returned if "data-id" attribute will be missing on element.
    public DataProvider<int?, TOwner> DataId => Attributes.Get<int?>("data-id");
}
```

`Should` will work with each of these `DataProvider` properties.

**Comment by auriou** [comment]
Perfect, I will use this syntax. 
Is it possible to test if the url of the image is valid or the image tag displays an image

**Comment by YevgeniyShunevych** [comment]
There is an option to check is the image is loaded using JavaScript. Here is the working example:

```cs
namespace Atata
{
    [ControlDefinition("img")]
    public class Image<TOwner> : Control<TOwner>
        where TOwner : PageObject<TOwner>
    {
        public DataProvider<string, TOwner> Source => Attributes.Src;

        public DataProvider<bool, TOwner> IsLoaded => GetOrCreateDataProvider("loaded state", GetIsLoaded);

        protected virtual bool GetIsLoaded()
        {
            return (bool)Driver.ExecuteScript("return arguments[0].complete && typeof arguments[0].naturalWidth != \"undefined\" && arguments[0].naturalWidth > 0", Scope);
        }
    }
}
```

```cs
Go.To<SomePage>().
    SomeImage.Source.Should.EndWith("/images/some-image.png").
    SomeImage.IsLoaded.Should.BeTrue();
```

I will probably add this class to the next version of Atata. Maybe any other suggestions related to image control?

**Comment by auriou** [comment]
great, thank you.

sometimes, I have pages that make it take time to get back to the .net testing program. is there an option to limit the loading time, and omit the loading of all the hits (external links)
