### ISSUE TITLE
ChromeOption AddUserProfilePreference 

### ISSUE THREAD

**Issue by msbhatt2018** [atata-framework/atata#186]
I want to change the default download directory similar to:
 chromeOptions.AddUserProfilePreference("download.default_directory", @"D:\DataTest");

How can I do this in ChromeAtataContextBuilder?

Thanks.

**Comment by YevgeniyShunevych** [comment]
To configure driver options use one of `WithOptions` methods:

```cs
AtataContext.Configure().
    UseChrome().
        WithOptions(opt => opt.AddUserProfilePreference("download.default_directory", @"D:\DataTest")).
    //...
    Build();
```

Whole list of driver configuration methods can be found on [Set Up/Driver](https://atata-framework.github.io/getting-started/#driver) page.

**Comment by msbhatt2018** [comment]
Thanks
