### ISSUE TITLE
Cannot find File Input Control with Atata

### ISSUE THREAD

**Issue by MonzT** [atata-framework/atata#188]
Hi :) 

Me again. 

I'm attempting to use the File Input control in the following Manner:

> <div class="form-inline image-select">
      <div class="custom-file" data-automation="File-ImagesSelector">
        <input type="file" class="custom-file-input" id="customFile" data-automation="selectImages" (change)="changeListener($event)" accept=".png, .jpg, .jpeg" multiple >
        <label class="custom-file-label text-truncate" for="customFile">Select Images</label>
      </div>

```
> [FindById("customFile")]
public FileInput<_> AddImagesSelector { get; private set; }

```
However, I get the following error when trying to do so:

`Message: OpenQA.Selenium.NoSuchElementException : Unable to locate element: By.XPath: .//*[normalize-space(@id) = 'customFile']/descendant-or-self::input[@type='file']Context element:Tag: bodyLocation: {X=0,Y=0}Size: {Width=929, Height=294}Text: Media ImagesSelect `

If I use pure selenium as below, I can find and use the control as normal:

`driver.FindElement(By.Id("customFile")).SendKeys("path");`

am I missing something here that Atata needs?

**Comment by YevgeniyShunevych** [comment]
Hi,

Yep, there is an issue of `FileInput<TOwner>` that works with hidden `<input type="file">` (CSS `opacity: 0`, etc.).

I will need to update `FileInput<TOwner>` control class in upcoming version of Atata. Anyway, you can bypass this issue by using this class instead:

```cs
[ControlDefinition("input[@type='file']", Visibility = Visibility.Any)]
public class HiddenFileInput<TOwner> : Input<string, TOwner>
    where TOwner : PageObject<TOwner>
{
    protected override void SetValue(string value)
    {
        string valueAsString = ConvertValueToString(value);
        Scope.SendKeys(valueAsString);
    }
}
```

**Comment by MonzT** [comment]
awesome! thank you so much. looking forward to the update. 

In the mean time, the work around does the trick. 

Thank you again!
