### ISSUE TITLE
Screenshot on Failure

### ISSUE THREAD

**Issue by dwelsh1** [atata-framework/atata#2]
Hello,

Does Atata support any options with taking screenshots. For example I want to take screenshots only on fails.

Thanks

**Comment by YevgeniyShunevych** [comment]
Yes, there is a functionality for taking screenshots. First you need to extend AtataContext initialization on set-up:

```C#
AtataContext.Build().
    // Do some initialization.
    AddScreenshotFileSaving(() => $@"Logs\{AtataContext.BuildStart:yyyy-MM-dd HH_mm_ss}\{AtataContext.Current.TestName}").
    // You can specify any folder path.
        With(ImageFormat.Png). // Optionally you can specify screenshot file format. Png is used by default.
    SetUp();
```

Also you can use `AddScreenshotConsumer` method that accepts instance of `IScreenshotConsumer` interface, that you can implement for any custom screenshot processing functionality (for example, upload to some server).

And finally for taking screenshot on test failure here are 2 ways to handle using NUnit:
1. On TearDown:
```C#
[TearDown]
public void TearDown()
{
    if (TestContext.CurrentContext.Result.Outcome.Status == TestStatus.Failed)
        AtataContext.Current.Log.Screenshot("Failed");

    AtataContext.Current.CleanUp();
}
```
2. On Atata's CleanUp:
```C#
AtataContext.Build().
    // Do some initialization.
    OnCleanUp(() =>
    {
        if (TestContext.CurrentContext.Result.Outcome.Status == TestStatus.Failed)
            AtataContext.Current.Log.Screenshot("Failed");
    }).
    SetUp();
```

In addition you can use [Screenshot trigger](https://atata-framework.github.io/triggers/#screenshot) if you need to take screenshots during test execution at some points.

**Comment by YevgeniyShunevych** [comment]
On latest [Atata 0.11.4](https://www.nuget.org/packages/Atata/0.11.4) I extended screenshots functionality. Added an option to configure the file name format and added `TakeScreenshotOnNUnitError` extension method for `AtataContextBuilder`.

So currently for your case you can do the following:
```cs
AtataContext.Build().
    // Do some initialization.
    AddScreenshotFileSaving().
        WithFolderPath(() => $@"Logs\{AtataContext.BuildStart:yyyy-MM-dd HH_mm_ss}").
        WithFileName(screenshotInfo => $"{AtataContext.Current.TestName} - {screenshotInfo.PageObjectFullName}").
    TakeScreenshotOnNUnitError().
    SetUp();
```

Find out more about screenshots on [Atata Docs - Screenshots](https://atata-framework.github.io/getting-started/#screenshots).
