### ISSUE TITLE
.NET Core Support

### ISSUE THREAD

**Issue by neooleg** [atata-framework/atata#22]
Hi everybody,

could you please support .NET Core and provide ability to run on Linux and Mac OS X?

It might be challenge to connect WebDriver on Linux/OS X, however, it will hugely promote the framework ahead.

Thanks!

**Comment by IlyaSelivanov** [comment]
Hi, sure, I’ll try to do this.

Sent from Mail for Windows 10

From: Oleg V.
Sent: 2 мая 2017 г. 7:36
To: atata-framework/atata
Cc: Subscribed
Subject: [atata-framework/atata] .NET Core Support (#22)

Hi everybody,
could you please support .NET Core and provide ability to run on Linux and Mac OS X?
It might be challenge to connect WebDriver on Linux/OS X, however, it will hugely promote the framework ahead.
Thanks!

**Comment by neooleg** [comment]
Pls share _any results (even a bad one)_ of the experiments/investigation here. This will be useful anyway!

**Comment by YevgeniyShunevych** [comment]
Hi,

I am going to add support of .NET Core or NetStandard, but after Selenium WebDriver will be updated to support it.

**Comment by IlyaSelivanov** [comment]
Hi.

Win10 x64; VS 2017

Guthub url: https://github.com/atata-framework/atata.git

Build error:  

This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  

The missing file is c:\...\AtataTest\\.nuget\NuGet.targets.	

Atata	C:\...\Repos\atata\src\Atata\Atata.csproj


I have refreshed dependencies, but still have got that error.

Sorry if it poor info, but I was going to build it on windows first, than try to move it on Ubuntu 16.04 (VirtualBox).

Sent from Mail for Windows 10

**Comment by IlyaSelivanov** [comment]
One more thing:

I've builded Atata solution with .Net 4.0. Then I added referencies to compiled dll files to my .Net Core 1.1 (console app) project. 

I have got the above exception at runtime:

System.IO.FileNotFoundException: 'Could not load file or assembly 'Atata, Version=0.11.4.0, Culture=neutral, PublicKeyToken=null'.

**Comment by YevgeniyShunevych** [comment]
Hi Ilya,

Just installed the latest version of VS 2017 Community on Win10 x64. Cloned Atata repository and, for me, project and solution opens and build without any problems. You can also try to clone repository to another folder. And check if you have release version of VS 2017.

Any way, how do you plan to support .NET Core? Atata references WebDriver which is not .NET Core compatible, it uses .NET 4.0.

**Comment by IlyaSelivanov** [comment]
Hi.

One more thing:

I've builded Atata solution with .Net 4.0. Then I added referencies to compiled dll files to my .Net Core 1.1 (console app) project. 

I have got the above exception at runtime:

System.IO.FileNotFoundException: 'Could not load file or assembly 'Atata, Version=0.11.4.0, Culture=neutral, PublicKeyToken=null'.

“Any way, how do you plan to support .NET Core? Atata references WebDriver which is not .NET Core compatible, it uses .NET 4.0.”
I believe this can help me: 
https://www.nuget.org/packages/Microsoft.NETCore.Portable.Compatibility
, at least to run it with minimum required initalization.

**Comment by YevgeniyShunevych** [comment]
.NET Core assemblies can reference only .NET Core/NetStandard assemblies, not .NET 4.0. As WebDriver is .NET 4.0, we cannot reference it even if Atata (currently .NET 4.0) will be updated to be .NET Core assembly. There is a discussion https://github.com/SeleniumHQ/selenium/pull/2269 regarding support of .NET Core by WebDriver. We have to wait until Selenium will release .NET Core version of WebDriver. Selenium team replied that they are going to support .NET Core staring 2.0 version, which is planned to be released by Microsoft in 2017 Q3. There is [CoreCompat.Selenium.WebDriver](https://www.nuget.org/packages/CoreCompat.Selenium.WebDriver/) NetStandard compatible version of WebDriver, but it is unofficial build of WebDriver, and I am not going to support it (at least now).

**Comment by IlyaSelivanov** [comment]
Got it. This manipulations have no sense. Thank you for good explanation.

**Comment by YevgeniyShunevych** [comment]
Welcome. Besides, not all types and members from full .NET are present on .NET Core/Standard. Currently Atata project is 98.54% compatible with upcoming .NET Core 2.0, and 96.94% with .NET Standard 2.0. I will need to make some code changes to make it completely compatible. But any way, we have to wait for Selenium for WebDriver update.

**Comment by neooleg** [comment]
> and I am not going to support it (at least now).
This is a great idea. At least it will allow to test Atata yet for .NET Core/Standard compatibility, i.e. it will allow to be ready at day 1 for WebDriver release.

**Comment by DimaDubyk** [comment]
Core2.0 is supported by webdriver from now. http://jimevansmusic.blogspot.ru/2017/09/selenium-webdriver-support-for-net-core.html

**Comment by YevgeniyShunevych** [comment]
Thanks, I know. I will publish next release of Atata with .NET Standard 2.0 support soon.

**Comment by YevgeniyShunevych** [comment]
[Atata 0.15.0 Released](https://atata-framework.github.io/blog/2017/10/12/atata-0.15.0-released/) with .NET Core/Standard 2.0 support. Please try and let me know if you face any issue.
