### ISSUE TITLE
Setting download folder location for Chrome

### ISSUE THREAD

**Issue by MonzT** [atata-framework/atata#225]
hi there. 

I am trying to change the default download location of chrome that isn't C:\users\profile\downloads.
I noticed in the JSON Config project that you have the following:

```
 "userProfilePreferences": { // Chrome and Opera specific.
                                  // Dictionary of preferenceName and preferenceValue.
                                  // Invokes AddUserProfilePreference method of driver specific options (e.g., ChromeOptions) for each item.
        "pref1": false,
        "pref2": "str"
      }
```
I've tried implementing it as follows, but it's not working as expected

**Implementation 1**
```
 "userProfilePreferences": { 
       "download.default_directory": "@\\customFileLocation\"
      }
```
**Implementation 2**

```
            string downloadUrl = "@\\customFileLocation\";
            var a = AtataContext.Configure();

            Dictionary<string, object> options= new Dictionary<string, object>();
            options.Add("download.default_directory", downloadUrl);

            a.UseChrome().WithLocalDriverPath().WithArguments("--start-maximized").WithOptions(options);
```

Is there another way to do it? 

Any help would be appreciated!

Kind Regards

**Comment by YevgeniyShunevych** [comment]
Hi,

I guess that you can have an issue because of `@` character inside path `"@\\customFileLocation\"`. Just remove it, if it is present in your actual code. Also, single `\` is invalid at the end of JSON string. Eeither replace it with `\\` or just remove it, as trailing backslash is not required in this path.

Using `Atata.Configuration.Json` the following is valid in JSON:

```json
"driver": {
  "type": "chrome",
  "options": {
    "arguments": [ "disable-extensions", "start-maximized", "disable-infobars" ],
    "userProfilePreferences": {
      "download.default_directory": "C:\\temp"
    }
  }
}

```

Using `AtataContextBuilder`:

```cs
AtataContext.Configure().
    UseChrome().
        WithOptions(opt => opt.AddUserProfilePreference("download.default_directory", @"C:\some\path")).
        //...
```
