### ISSUE TITLE
Atata webdriver can't find controls on Angular app

### ISSUE THREAD

**Issue by ianstagib** [atata-framework/atata#227]
Hi, I'm having issues with the webdriver in my basic atata project finding controls on my angular app. I have created a stackoverflow question which I'll link here to save the double typing. 

https://stackoverflow.com/questions/53428984/atata-selenium-web-driver-cant-find-controls-by-id-on-angular-app

Is there a bug in the current version of atata on .netcore that could be causing this issue?

**Comment by YevgeniyShunevych** [comment]
Hi. Posted comment on StackOverlow. Please check.

**Comment by ianstagib** [comment]
I marked your reply as the answer. Thanks so much Yevgeniy, you rock.

**Comment by YevgeniyShunevych** [comment]
Welcome and thanks. Feel free to ask on GitHub or StackOverflow. I try to monitor [`atata` tag](https://stackoverflow.com/questions/tagged/atata) on SO.
