### ISSUE TITLE
WebDriver Actions support

### ISSUE THREAD

**Issue by DimaDubyk** [atata-framework/atata#25]
There is no support for WebDriver Actions. So there is no possibility to drag-n-drop and do other complex actions.

**Comment by YevgeniyShunevych** [comment]
WebDriver API as well as `Actions` is not wrapped/hidden and is completely accessible.

Here is the sample of control that can be dragged to some container:
```cs
public class SomeControl<TOwner> : Control<TOwner>
    where TOwner : PageObject<TOwner>
{
    /// <summary>
    /// Drags and drops current control to container.
    /// </summary>
    public TOwner DragAndDropToContainer()
    {
        IWebElement targetContainerElemnt = Driver.Get(By.Id("some-container"));

        // Use WebDriver native Actions functionality.
        Actions actions = new Actions(Driver);
        actions.DragAndDrop(Scope, targetContainerElemnt).Perform(); // Scope is IWebElement instance representing current control element.

        // Or use Atata's Perform extension method to simplify the code.
        Driver.Perform(x => x.DragAndDrop(Scope, targetContainerElemnt));

        return Owner;
    }
}
```
Besides, anywhere in the code you can access `RemoteWebDriver` instance using `AtataContext.Current.Driver` and perform any native `WebDriver` actions. It's absolutely OK to combine Atata's code with native WebDriver's.

Trigger sample:
```cs
/// <summary>
/// Defines the keys to press on the specified event. By default occurs after the set.
/// </summary>
public class PressKeysAttribute : TriggerAttribute
{
    public PressKeysAttribute(string keys, TriggerEvents on = TriggerEvents.AfterSet, TriggerPriority priority = TriggerPriority.Medium)
        : base(on, priority)
    {
        Keys = keys;
    }

    public string Keys { get; protected set; }

    protected internal override void Execute<TOwner>(TriggerContext<TOwner> context)
    {
        if (!string.IsNullOrEmpty(Keys))
        {
            context.Driver.Perform(x => x.SendKeys(Keys));
        }
    }
}
```

**Comment by DimaDubyk** [comment]
Now I use native webDriver code in tests for DragAndDrop action but I want to have access to Scope. In this case I am able to do like:

    `new Actions(AtataContext.Current.Driver).DragAndDrop(sourceControl.Scope, targetControl.Scope).Build().Perform();`

instead of  searching elements explicitly (at least targetControl if I use you example in code).

**Comment by YevgeniyShunevych** [comment]
I see your issue. Scope is not accessible as it is `protected internal` currently. Just 2 days ago implemented issue: #24 Make UIComponent.Scope property public. It will be present in upcoming 0.13.0 version. For now, you can cast control to `IUIComponent<_>` to get access to more control members:
```cs
((IUIComponent<_>)sourceControl).Scope
```

**Comment by DimaDubyk** [comment]
Thanks, it helped.

**Comment by YevgeniyShunevych** [comment]
Welcome.
