### ISSUE TITLE
Please add support for netcoreapp2.0 to published nuget pacakge

### ISSUE THREAD

**Issue by ravensorb** [atata-framework/atata#256]
It looks like the currently published package doesn't support .NET Core App 2.0 -- can you add support?

```
The nuget command failed with exit code(1) and error(Errors in D:\a\1\stest\test.csproj
    Package Atata 1.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Atata 1.0.0 supports:
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - netstandard2.0 (.NETStandard,Version=v2.0)
    One or more packages are incompatible with .NETCoreApp,Version=v2.0.)
Packages failed to restore
```

**Comment by YevgeniyShunevych** [comment]
.NET Core 2.0 is supported by Atata v1.0.0 by having .NET Standard 2.0 version and it is tested. Here is a simple sample project [atata-samples/NetCore.NUnit](https://github.com/atata-framework/atata-samples/tree/master/NetCore.NUnit) that uses .NET Core 2.0. How you build your project or restore the packages, what command do you use?

**Comment by ravensorb** [comment]
Odd -- the error above is right out of dotnet cli -- any ideas why using dotnet cli cannot install/restore give an error indicating it is not supported?

**Comment by YevgeniyShunevych** [comment]
I have not faced such an issue using dotnet cli. Could you specify exactly the command text that you execute? Can it be reproduced on another machine? If it is possible please share sample project sources that you try to build.

**Comment by ravensorb** [comment]
Ok, I think I see what the issue is -- nuget restore and restore using vs cli is failing -- dotnet restore is working.  Seems that both nuget and vs cli are looking for netcoreapp2.0 to be explicitly defined in the targetframeworks where dotnet cli is a bit more forgiving.  The hard part is, this means that using a number of the build tools out there (cake, jenkins, Azure DevOps) will not work as expected.
