### ISSUE TITLE
Take screenshot of page object

### ISSUE THREAD

**Issue by cakriwut** [atata-framework/atata#281]
Hi,

How can we take screenshot of a page on document loaded?

Thanks.

**Comment by YevgeniyShunevych** [comment]
Hey,

You can simply mark your page object class with `ScreenshotAttribute` with `TriggerEvents.Init` as follows:

```cs
[Screenshot(on: TriggerEvents.Init)]
public class SamplePage : Page<_>
{
}
```

But if your page is dynamic and you have to wait a bit before it is loaded you can also add another trigger for page load [waiting](https://atata.io/triggers/#waiting) like:

```cs
[WaitForDocumentReadyState(on: TriggerEvents.Init, priority: TriggerPriority.High)]
[Screenshot(on: TriggerEvents.Init, priority: TriggerPriority.Medium)]
public class SamplePage : Page<_>
{
}
```

**Comment by cakriwut** [comment]
Thanks a lot, it works.
