### ISSUE TITLE
References could not be found

### ISSUE THREAD

**Issue by visma-jonhygomgislason** [atata-framework/atata#283]
I am just starting out with Atata, hoping I can use it as a replacement for Coded UI.

When I attempt to create a new Atata NUnit Test Project (.NET Framework) in either Visual Studio 2017 or 2019, all references, not limited to just Atata related components, but also all standard components, such as System and Microsoft.CSharp, cannot be found.

See attached screenshots for full list of references.

![image](https://user-images.githubusercontent.com/17744314/58874169-563e1080-86c8-11e9-9008-aeb9b68db04f.png)

![image](https://user-images.githubusercontent.com/17744314/58874287-aae18b80-86c8-11e9-9a41-2e125362a890.png)

**Comment by YevgeniyShunevych** [comment]
Have you tried to build/rebuild the solution in Visual Studio? Project dependency packages should be loaded from NuGet during the build.

**Comment by visma-jonhygomgislason** [comment]
I have, I simply receive the same error.

**Comment by visma-jonhygomgislason** [comment]
I've tried to delete the references, then manually add it in from the packages folder in the project, where all the Atata related references are present. I still receive the same error.

**Comment by YevgeniyShunevych** [comment]
I don't know. Something strange. You can try to create a regular .NET class library project and try to add any NuGet packages (Atata, NUnit, etc.) to it, build and check.

**Comment by cakriwut** [comment]
Did you start from project type Library? I have no problem following Wiki instruction.

**Comment by visma-jonhygomgislason** [comment]
I've been following this guide: https://atata.io/getting-started/
Strangely, if I try to create a .NET Core Atata Project, all dependencies will initially show as unable to be found, then becomes available.
I will try creating a regular .NET class library project and adding the packages, then update here on the outcome.

**Comment by visma-jonhygomgislason** [comment]
I was able to create a regular .NET class library project and all all the NuGet packages, then copy hte contents of the AtataSettings.cs, NUnitSettings.cs and UItestFixture.cs classes.

I still don't understand what happened, but I should be able to use .NET Core for our needs. Thanks for the help.
