### ISSUE TITLE
How to handle windows authentication dialog?

### ISSUE THREAD

**Issue by cakriwut** [atata-framework/atata#284]
Hi,

My web application uses NTLM authentication, and the browser will show authentication dialog window when we first open the web.
How can I handle the authentication dialog?

**Comment by YevgeniyShunevych** [comment]
Hi,

Oh, there is no simple single solution for WebDriver as well as for Atata for now. It depends on actual browser kind.

You can try to google about WebDriver NTLM authetication for your browser ([like for Firefox](https://stackoverflow.com/questions/54647594/handling-windows-ntlm-authentication-with-selenium-webdriver).

Then you can try to apply extra configuration during `AtataContext` configuration:

```cs
AtataContext.Configure().
    UseFirefox().
        WithOptions(options =>
        {
            // Configure FirefoxOptions...
        }).
```

**Comment by YevgeniyShunevych** [comment]
Hey,

Here is also a fresh article series [Handling Authentication Requests with Selenium](http://jimevansmusic.blogspot.com/2019/05/handling-authentication-requests-with.html) from Jim Evans including an article about NTLM Authentication. May be useful.
