### ISSUE TITLE
How to get the label of an input text?

### ISSUE THREAD

**Issue by hamiltonmarques** [atata-framework/atata#287]
Hi!

It's my second week working with Atata and I'm enjoying.
Is there a way to get the label of a input text or should I map the label as another element?

**Comment by YevgeniyShunevych** [comment]
Hey,

I've just posted new Atata example: [Verification of Labels](https://atata.io/examples/verification-of-labels/). It should be what you are looking for.

**Comment by hamiltonmarques** [comment]
Nice! Thanks!
