### ISSUE TITLE
Handle fast loading element

### ISSUE THREAD

**Issue by hamiltonmarques** [atata-framework/atata#288]
Hi!
I'm using the code below to wait a loading after to click a button.
```csharp
   [FindById("buttonId")]
   [WaitForElement(WaitBy.Id, "divloading", Until.VisibleThenHidden)]
   public Button<_> MyButton { get; private set; }
```
```html
<div id="divloading" style="display: none;">
            <div class="overlay"></div>
            <div class="modal33">
                <div class="windows8">
                    <div class="wBall" id="wBall_1">
                        <div class="wInnerBall"></div>
                    </div>
                    <div class="wBall" id="wBall_2">
                        <div class="wInnerBall"></div>
                    </div>
                    <div class="wBall" id="wBall_3">
                        <div class="wInnerBall"></div>
                    </div>
                    <div class="wBall" id="wBall_4">
                        <div class="wInnerBall"></div>
                    </div>
                    <div class="wBall" id="wBall_5">
                        <div class="wInnerBall"></div>
                    </div>
                </div>

                <span style="display: block; color: white; font-weight: 600; margin-top: -50px; font-size: 15px;">Wait...</span>
            </div>
        </div>
```
Sometimes it appears and disappears so fast that Atata throws it's not visible.
I've tried to fix decreasing UseBaseRetryInterval to 20 milliseconds for example, but with no success.
Is there a way to handle this?

**Comment by YevgeniyShunevych** [comment]
Hey,

You can use additional properties of `WaitForElementAttribute` for loading sections that not always become visible this way:

```cs
[WaitForElement(WaitBy.Id, "divloading", Until.VisibleThenHidden, PresenceTimeout = 2, ThrowOnPresenceFailure = false)]
```

The above means that it should wait 2 seconds for the element to become visible and do not throw exception if it is not visible, just continue.

**Comment by hamiltonmarques** [comment]
**Awesome!**
Thanks!
Is there a way to declare WaitForElement only once to use with various elements?
I googled and found it's not possible, but maybe with Atata is.

**Comment by YevgeniyShunevych** [comment]
For the cases when there is a need to reuse the same trigger in many places, you can create a class inherited from `WaitForElementAttribute` and extract settings to it:

```cs
public class WaitForLoadingIndicatorAttribute : WaitForElementAttribute
{
    public WaitForLoadingIndicatorAttribute(TriggerEvents on = TriggerEvents.AfterClick, TriggerPriority priority = TriggerPriority.Medium)
        : base(WaitBy.Id, "divloading", Until.VisibleThenHidden, on, priority)
    {
        PresenceTimeout = 2;
        ThrowOnPresenceFailure = false;
    }
}
```

Use it on page object:

```cs
[WaitForLoadingIndicator(TriggerEvents.Init)] // Wait upon page initialization.
public class SomePage : Page<_>
{
    [FindById("buttonId")]
    [WaitForLoadingIndicator] // Wait after button click.
    public Button<_> MyButton { get; private set; }
}
```

**Comment by hamiltonmarques** [comment]
**Nice!**
Thanks!

**Comment by YevgeniyShunevych** [comment]
Welcome.

**Comment by hamiltonmarques** [comment]
Hi!
Sorry for reopen the issue. I closed it without testing (unacceptable mistake).
Something is not working.
I used your code and now Atata is not waiting element to hide.
Looks like Atata waits only 2 seconds and goes to next command.
My BaseRetryTimeout is 20 seconds.
Could you check this please?

**Comment by YevgeniyShunevych** [comment]
Hey. How long it takes to `"divloading"` to become visible? It may be that 2 seconds are not enough. If so, increase `PresenceTimeout` to some greater value.

**Comment by hamiltonmarques** [comment]
Hi!
Increasing `PresenceTimeout` worked fine.
But it's strange because `"divloading"` becomes visible within less than 2 seconds apparently.
Thanks anyway!
