### ISSUE TITLE
How to define alert in page class?

### ISSUE THREAD

**Issue by FrameBassman** [atata-framework/atata#289]
Hi

I want to test the following application: https://romashov.tech/chat
This is code of my MainPage:

```
using Atata;
using _ = Chat.Tests.Model.MainPage;

namespace Chat.Tests.Model
{
    [Url("")]
    public class MainPage : Page<_>
    {
        [FindById("send")]
        public Button<_> Send { get; private set; }
    }
}
```

When I run my test I have the following exception:
`OpenQA.Selenium.UnhandledAlertException : unexpected alert open: {Alert text : Your name:}
  (Session info: chrome=75.0.3770.100)`

How I can define it in page class?
How I can put nickname in this allert?

**Comment by YevgeniyShunevych** [comment]
Hi,

You can add a method (`EnterAs` or somehow else) to your page object which will handle prompt alert using WebDriver API:

```cs
using Atata;
using OpenQA.Selenium;

namespace Chat.UITests
{
    using _ = MainPage;

    public class MainPage : Page<_>
    {
        [FindFirst]
        public TextInput<_> Message { get; private set; }

        [FindByClass("send-button")]
        public Button<_> Send { get; private set; }

        public _ EnterAs(string name)
        {
            IAlert alert = Driver.SwitchTo().Alert();
            alert.SendKeys(name); // Note that SendKeys doesn't work in Chrome for a long time. Works in Firefox for example.
            alert.Accept();

            Driver.SwitchTo().DefaultContent();

            return Owner;
        }
    }
}
```

Then use it in the test this way:

```cs
Go.To<MainPage>().
    EnterAs("SomeUser").
    Message.Set("test message").
    Send.Click();
```

**Comment by FrameBassman** [comment]
@YevgeniyShunevych seems, that `alert.SendKeys` works on Chrome)

**Comment by YevgeniyShunevych** [comment]
This is cool then. It was not working for me in Chrome. On what version of ChromeDriver and Chrome it worked for you?
