### ISSUE TITLE
Hide console window of chromedriver.exe

### ISSUE THREAD

**Issue by siquylee** [atata-framework/atata#291]
How can I hide the console window of chromedriver.exe? It can be done with Selenium for C# (see https://stackoverflow.com/questions/35818436/hide-silence-chromedriver-window) but I don't know to do with Atata framework

**Comment by YevgeniyShunevych** [comment]
Here is the sample:

```cs
AtataContext.Configure().
    UseChrome().
        WithArguments("headless").
        WithDriverService(x => x.HideCommandPromptWindow = true).
    //...
    Build();
```

**Comment by siquylee** [comment]
Thanks, it works fine.
