### ISSUE TITLE
Add ImageInput component field

### ISSUE THREAD

**Issue by alex-gagnon** [atata-framework/atata#294]
Requesting there to be an addition of an ImageInput component with INavigable option. I created a ControllerDefinition for one, but I'm not sure what your guidelines are for contributions, if you accept them at all.

**Comment by YevgeniyShunevych** [comment]
`ImageInput<TOwner>` and `ImageInput<TNavigateTo, TOwner>` controls are added to Atata in recently released [Atata 1.3.0](https://atata.io/blog/2019/09/17/atata-1.3.0-released/).

Issues: #307 and #308.

**Comment by bokoblin-link** [comment]
I removed my custom ImageInputs, updated to the most recent Atata build, and ran my existing tests successfully.
