### ISSUE TITLE
[Question] How to use AtataContext.Current.Driver.WindowHandles

### ISSUE THREAD

**Issue by bokoblin-link** [atata-framework/atata#295]
I am currently creating automated tests where every nearly every input type='image', 'button', etc. opens a new window. Currently, getting an ArgumentOutOfRangeException when trying to use Go.ToNextWindow<MyPage>, but I believe that is because at that point I already have two browser windows open. 

I'm trying to use Go.ToWindow<MyPage>(...) while using a custom ImageInput component that mimics Button\`1.cs and Button\`2.cs. However, I'm not sure how to use AtataContext.Current.Driver.WindowHandles as specified in the Examples page.

Should I continue this route? or try to figure out how to close each previous browser window?

Edit: tried directly inputting the name from dev console `> window.name', but it came back with NoSuchWindowException

**Comment by YevgeniyShunevych** [comment]
I have a prototype of 2 extension methods for navigable buttons that switch the window.

```cs
using System.Linq;
using OpenQA.Selenium.Support.UI;

namespace Atata
{
    public static class IWindowNavigableExtensions
    {
        public static TNavigateTo ClickAndGoToNextWindow<TNavigateTo, TOwner>(this INavigable<TNavigateTo, TOwner> navigableControl)
            where TNavigateTo : PageObject<TNavigateTo>
            where TOwner : PageObject<TOwner>
        {
            AtataContext context = AtataContext.Current;

            int windowsCount = context.Driver.WindowHandles.Count;

            navigableControl.Click();

            string waitActionMessage = $"Wait until window is open";
            context.Log.Start(waitActionMessage, LogLevel.Trace);

            WebDriverWait wait = new WebDriverWait(context.Driver, context.WaitingTimeout)
            {
                PollingInterval = AtataContext.Current.WaitingRetryInterval,
                Message = waitActionMessage
            };
            wait.Until(driver => driver.WindowHandles.Count > windowsCount);

            context.Log.EndSection();

            return Go.ToNextWindow<TNavigateTo>();
        }

        public static TNavigateTo ClickAndGoToPreviousWindow<TNavigateTo, TOwner>(this INavigable<TNavigateTo, TOwner> navigableControl)
           where TNavigateTo : PageObject<TNavigateTo>
           where TOwner : PageObject<TOwner>
        {
            AtataContext context = AtataContext.Current;

            string currentWindowHandle = context.Driver.CurrentWindowHandle;

            string previousWindowHandle = context.Driver.WindowHandles.
                TakeWhile(x => x != currentWindowHandle).
                Last();

            navigableControl.Click();

            string waitActionMessage = $"Wait until \"{currentWindowHandle}\" window is closed";
            context.Log.Start(waitActionMessage, LogLevel.Trace);

            WebDriverWait wait = new WebDriverWait(context.Driver, context.WaitingTimeout)
            {
                PollingInterval = AtataContext.Current.WaitingRetryInterval,
                Message = waitActionMessage
            };
            wait.Until(driver => !driver.WindowHandles.Contains(currentWindowHandle));

            context.Log.EndSection();

            return Go.ToWindow<TNavigateTo>(previousWindowHandle);
        }
    }
}
```

You can copy this class to your project. You will be able instead of `SomeButton.ClickAndGo()` use `SomeButton.ClickAndGoToNextWindow()`

**Comment by bokoblin-link** [comment]
I've put the class into my project and can successfully call it. However, looking at the logs, it seems that after using `myCustomComponent.ClickAndGoToNextPage()` tests such as `Header.Should.Equal("bla bla bla")` are not being run - resulting in the tests always passing.

**MyTest**
`Login();
Go.ToNextWindow().  // Goes to Home page
    MyCustomComponent.ClickAndGoToNextWindow().
        Header.Should.Equal("Some words");
`

**HomePage**
`
lots of stuff....

[FindById("...")]
public ImageInput<ANewPage, _> MyCustomComponent { get; private set; }
`

ImageInput can be found here if I'm doing something wrong with them,
https://gist.github.com/bokoblin-link/c91d493a4c7cfc6589db124f9e1b46da

**Comment by YevgeniyShunevych** [comment]
Very strange. Used these methods many times and had no issues related to them. I see nothing suspicious in your code. You can try to do some other actions after `ClickAndGoToNextWindow` and maybe debug a bit.

**Comment by bokoblin-link** [comment]
I managed to figure out what the issue was. I had moved the directory of my custom controls resulting in them not being found when building the solution. I moved them back to a valid directory and now the tests run correctly.

Found the errors by clicking Build on the solution - they did not appear when I simply ran the tests.

Thank you so much!

**Comment by YevgeniyShunevych** [comment]
Sure, welcome.
