### ISSUE TITLE
[Question] How to use InvokeMethod with a select dropdown that becomes hidden on click

### ISSUE THREAD

**Issue by bokoblin-link** [atata-framework/atata#296]
Have another question for an awkward select field that becomes hidden when clicked and an input field becomes visible. I've been trying to use the InvokeMethod with BeforeClick and AfterClick Trigger Events to handle selecting options in a select field that becomes hidden when clicked.

Opening select field dropdown causes the select element and all options to become hidden and the input becomes visible. This makes it difficult to select a dropdown option. Even tried sending keys to the input field, but element says it is hidden again at that point.

Examples
**Before Select field click:**
```
<input id='some_input_id', **hidden**>
<select id='some_select_id', onchange='some_js'>
    <option value=0></option>
    <option value=1>p1</option>
</select>
```

**On Select field click**:
```
<input id='some_input_id'>
<select id='some_select_id', onchange='some_js', **hidden**>
    <option value=0></option>
    <option value=1>p1</option>
</select>
```

**MyPage.cs**
```
[FindById("some_input_id")]
public TextInput<_> SomeInput  { get; private set; }

[FindById("some_select_id")]
[InvokeMethod(nameof(OnBeforePerform), TriggerEvents.AfterClick)]
[InvokeMethod(nameof(OnAfterPerform), TriggerEvents.AfterClick)]
public Select<_> SomeSelect { get; private set; }

public void OnBeforePerform()
{
  SomeInput.Should.BeHidden();
}

public void OnAfterPerform()
{
  SomeInput.Wait(Until.Visible);
}
```

**MyTests.cs**
```
public class MyTests : UITestFixture
{
  [Test]
  public void DoTest()
  {
    // do some stuff
      SomeSelect.Click().
      SomeSelect.Set("some option").  // fails with or without SomeSelect.Click()
      SomeInput.Should.Be.Visible().  // fails
   // do some more stuff
  }
}
```

**Comment by bokoblin-link** [comment]
I figured out a temporary work around

MyTests.cs
```
// the setup
SomeSelect.Click().
Wait(10).  // wait 10 seconds, but could be shorter
SomeInput.Set("An option").  // not great, but works for now
SomeOtherComponent.Click().  // saves result
Wait(10).
SomeSelect.Should.Equal("An option").
// do more stuff
```

**Comment by YevgeniyShunevych** [comment]
I recommend extracting such steps to the custom control. The test should not know the nuances of the way the value is set to a particular input. So publically the test should do just `SomeSelect.Set("some option")`.

Here is how the custom control for such select can look like:

```cs
public class CustomSelect<TOwner> : Select<TOwner>
    where TOwner : PageObject<TOwner>
{
    [FindFirst(OuterXPath = "preceding-sibling::")]
    [TraceLog]
    [PressEnter] // Can be removed or replaced with [PressTab].
                 // This trigger is useful when after the value is set the "Enter" key pressing finishes the input.
    private TextInput<TOwner> AssociatedInput { get; set; }

    protected override void SetValue(string value)
    {
        Click();
        AssociatedInput.Set(value);
    }
}
```

Then just use this class in page object instead of regular `Select`.

Is your HTML select component custom or one from HTML component libraries? If it is a public component, we can modify this custom control class to be more correct.

**Comment by bokoblin-link** [comment]
Okay cool! Much easier to implement than I was anticipating and it makes the test code look magnitudes cleaner.

I ended up needing to add [FindSettings(Visibility = Visibility.Any)] to the class so that the Select element is still found. 

The only thing I'm trying to handle better with it is the fact that my dropdowns are dynamic. So whenever a selection or change is made, there is an overlay while it refreshes. So to circumvent this, I have an explicit wait of 'x' number of seconds after setting the AssociatedInput value in the CustomSelect.

```
...
AssociatedInput.Set(value).Wait(10);
```

What I would like to happen is for it to detect when another element <div id='i_am_updating'> starts as hidden -> becomes visible -> returns to hidden -> then continue my test.

I'm thinking I would add in something like 

```
// ...previous stuff
[FindLast(find the div element)]
private Control<TOwner> Overlay { get; set; }

protected override void SetValue(string value)
{
  Click();
  AssociatedInput.Set(value);
  Overlay.Wait(Until.VisibleThenHidden) // might need to play around with it
}

**Comment by YevgeniyShunevych** [comment]
Yes, you are going in the right direction. Also if your overlay element is commonly happening in your site, take a look at [Custom Trigger: Wait for Loading Indicator](https://atata.io/examples/custom-trigger-wait-for-loading-indicator/) example.

**Comment by bokoblin-link** [comment]
Okay, i went with the custom trigger since it wouldn't hurt to have it separate in the long run.

Unrelated but I guess the only thing I'm trying to determine how to do is working with composition instead of inheritance with page objects, since i may have multi-level inheritance I was getting a non-generic type error with a Base : Page Object<TOwner> -> Inherited : Base<_> -> SuperInherited : Inherited. 

Didn't seem like that would be a feasible way to go about it, so I was trying composition but I've had various issues with that.

**Comment by YevgeniyShunevych** [comment]
With inheritance you need to keep all base page object classes generic with `<TOwner>` like in [Page Object Inheritance](https://atata.io/examples/page-object-inheritance/) example.

And yes, it's absoultely OK to use composition by extracting common UI parts to custom controls. You can describe what issues you have got related to that.

**Comment by YevgeniyShunevych** [comment]
`MainMenuNavigation<TOwner>` and `SubNav1<TOwner>` should be inherited from `Control<TOwner>` instead of `PageObject<TOwner>`.

**Comment by bokoblin-link** [comment]
hahaha, i was going about making another control earlier today when that suddenly clicked for me. Thank you!

**Comment by YevgeniyShunevych** [comment]
Sure, welcome.
