### ISSUE TITLE
How to resize created window?

### ISSUE THREAD

**Issue by pipe01** [atata-framework/atata#312]
When using the Chrome driver with the `--headless` argument the window's size is set to 800x600, which causes responsive websites to appear like in mobile:

![01 - Log In page - Failed](https://user-images.githubusercontent.com/3885705/65168265-6e9e2500-da44-11e9-99a4-9ead0ec1308f.png)

Is there any way of setting the window's size to something bigger? I've tried adding a `--window-size="1000x1000"` argument but that causes Chrome to not open thus throwing an exception:

![image](https://user-images.githubusercontent.com/3885705/65168434-cd639e80-da44-11e9-8376-998025b2dd6e.png)

**Comment by YevgeniyShunevych** [comment]
You were too close. It should be `window-size=1000,1000`.

```cs
AtataContext.Configure().
    UseChrome().
        WithArguments("headless", "window-size=1000,1000").
    Build();
```

**Comment by pipe01** [comment]
That works, thank you!

**Comment by YevgeniyShunevych** [comment]
Welcome.
