### ISSUE TITLE
Why properties with type inherited from PageObject<T> aren't initialized in page?

### ISSUE THREAD

**Issue by OlegYanushkevich** [atata-framework/atata#314]
Hi @YevgeniyShunevych . I have one question. What logical difference between PageObject<TOwner> and Page<TOwner>? And what is PageObject<TOwner> in your project?
For me page object is logical part of page with own business logic. But in your framework page properties with types inherited from PageObject won't be initialized. Could you explain me that?

**Comment by YevgeniyShunevych** [comment]
Hey Oleg,

`PageObject` - is a base class for page objects. `Page` is a page object class inherited from `PageObject` and representing the whole HTML page. There is also [`PopupWindow`](https://atata.io/components/#popupwindow) class which can be used as a base class for popup window page objects.

Any way there should not be problems to inherit directly from `PageObject`. It's absolutely valid. Just recommended to define some `PageObjectDefinition` for this class with base XPath.

Could you share your page object class which get properties uninitialized?

**Comment by OlegYanushkevich** [comment]
Look, I have next page object and controls:

```csharp
[Url("/")]
    public class DevelopersHomePage : Page<DevelopersHomePage>
    {
        [FindById("build-profile-div")]
        public BuildProfilePageObject BuildProfilePageObject { get; set; }
        
        [FindById("build-profile-div")]
        public BuildProfileControl BuildProfileControl { get; set; }
    }

    public class BuildProfilePageObject : PageObject<BuildProfilePageObject>
    {
        [FindByClass("title")]
        public Content<string, BuildProfilePageObject> Title { get; set; }

        [FindByClass("description")]
        public Content<string, BuildProfilePageObject> Description { get; set; }
    }

    public class BuildProfileControl : Control<DevelopersHomePage>
    {
        [FindByClass("title")]
        public Content<string, DevelopersHomePage> Title { get; set; }

        [FindByClass("description")]
        public Content<string, DevelopersHomePage> Description { get; set; }
    }
```
In case getting  ```BuildProfile``` as ```PageObject``` I get null, but using ```BuildProfile``` as Control I get initialized object.

![image](https://user-images.githubusercontent.com/28996736/66036641-6c44cc00-e516-11e9-8770-264b4645f502.png)

Thanks for answer!

**Comment by YevgeniyShunevych** [comment]
Got it. Right, `PageObject` as part of other `PageObject` will not be initialized.

In the concepts of Atata, there should be a single active page object which can consist of controls, data providers and UI component parts; but not other page objects. You have to switch to another page object using `Go.To` or by using controls like `Link`, `Button`, etc. Some vast section of controls can be extracted to a separate control class and contain a set of its controls. It can look like hierarchy where the root is a page object and controls are nodes.

**Comment by OlegYanushkevich** [comment]
Clear, I understand. Thanks a lot of your describing.
