### ISSUE TITLE
Supporting finding page objects by Id.

### ISSUE THREAD

**Issue by OlegYanushkevich** [atata-framework/atata#315]
Hi @YevgeniyShunevych 

What do you think about adding finding ```UIComponents``` and ```PageObjects``` by Id(like finding by class/classes in [ScopeDefinitionAttribute](https://github.com/atata-framework/atata/blob/master/src/Atata/Attributes/ScopeDefinitionAttribute.cs)). For example:

```csharp
  [PageObjectDefinition("div", ContainingId = "some-id")]
    public class BuildProfilePageObject : PageObject<_>
    {
        [WaitFor(Until.Visible)]
        [FindByClass("title")]
        public Content<string, _> Title { get; private set; }

        [WaitFor(Until.Visible)]
        [FindByClass("description")]
        public Content<string, _> Description { get; private set; }

        [WaitFor(Until.Visible)]
        [FindByClass("text-decoration-none")]
        public Link<LoginFormPageObject, _> LoginOrRegister { get; private set; }
    }
```

I have some prototype of that, but want to hear what do you think about it.

**Comment by YevgeniyShunevych** [comment]
Currently, it is possible to set default locator do for controls this way:

```cs
[ControlDefinition("div")]
[FindById("some-id")]
public class SomeControl : Control<_>
{
}
```

For page objects, I'm not sure that something like this is needed. Currently it is possible to do it this way:

```cs
[PageObjectDefinition("div[@id='some-id']")]
```
