### ISSUE TITLE
[Question] Support async context

### ISSUE THREAD

**Issue by DimaDubyk** [atata-framework/atata#317]
@YevgeniyShunevych, @ysamus Hi,
Thank you for you efforts in supporting this project.
Do you have any plans to add support for AsyncLocal storage in AtataContext. Now it has only local thread and thread static support wich does not work well in async tests. https://github.com/atata-framework/atata/blob/master/src/Atata/Context/AtataContext.cs#L20
Our team is willing to help you implementing this if you decide to give green light)

**Comment by YevgeniyShunevych** [comment]
Hey @DimaDubyk. Your idea sounds interesting. Atata is not OK with async methods currently.

But we need to consider that `AsyncLocal` is supported in .NET 4.6+ and .NET Standard 2.0+. Currently Atata package is built with having 3 versions: .NET 4.0, .NET 4.5 and .NET Standard 2.0. I mean that `AsyncLocal` feature currently can exist in Atata only for .NET Standard 2.0 version, the other 2 versions should not contain this feature, as they can't.

As for implementation, I guess you want to replace `bool IsThreadStatic` property of `AtataContext` with enum having 3 option values. Or I might be wrong. Could you describe a bit your implementation thoughts? Or you can create a PR and we can continue the discussion there.

And another thing that we should consider is SemVer that Atata follows. So this feature should not contain breaking changes.

**Comment by DimaDubyk** [comment]
Hi, sorry for long response,
Yes, we consider adding enum instead of flag,
also adding Extension methods for context builder type setup are preferrable.
Should IsThreadStatic be marked as depricated to follow SemVer?

**Comment by YevgeniyShunevych** [comment]
No problem. Sounds good.

Yes, I usually mark such members with `ObsoleteAttribute`:

```cs
[Obsolete("Use {another property} instead.")] // Obsolete since v1.4.0.
```

**Comment by Piedone** [comment]
Any updates on this in the meantime, have you worked on this @DimaDubyk?

**Comment by Piedone** [comment]
Also, another, orthogonal solution would be to allow non-static usage of Atata. I.e. you build an `AtataContext` that you then carry yourself and use to run tests. This would need e.g. `Go()` to be somehow available by using a context supplied from the outside, as opposed to `AtataContext.Current`.

**Comment by DimaDubyk** [comment]
@Piedone Hi, sorry, no. We have found workaround for our case.

**Comment by YevgeniyShunevych** [comment]
I will implement `AsyncLocal` feature in this week.

**Comment by Piedone** [comment]
Fantastic, thank you @YevgeniyShunevych !

**Comment by YevgeniyShunevych** [comment]
`AsyncLocal` is implemented by #363 and just released with [Atata v1.5.0](https://atata.io/blog/2020/04/23/atata-1.5.0-released/).

**Comment by Piedone** [comment]
That's great, thank you Yevgeniy!

**Comment by Piedone** [comment]
What fixes this exactly, @YevgeniyShunevych?

**Comment by YevgeniyShunevych** [comment]
@Piedone, it makes `AtataContext.Current` property to use [`AsyncLocal<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.asynclocal-1?view=net-5.0) backing field when `AtataContext.ModeOfCurrent = AtataContextModeOfCurrent.AsyncLocal`.

For any specific scenarios, it is possible to save `AtataContext` instance, after it is built, to anywhere you want and reuse it in other threads, etc. It is absolutely not required to use `AtataContext.Current` property.

I don't know what else can be done here. Any ideas?

**Comment by YevgeniyShunevych** [comment]
OK, I missed that point. Right, good idea. I think it's even logical to move (make copies of) GoTo methods to `AtataContext` as instance methods:

```cs
atataContextInstance.GoTo<SomePage>()
```

Also update `Go` class to transfer the calls to newly added methods.

It should not be difficult. I can implement that in current 1.11.0 version of Atata.

**Comment by Piedone** [comment]
An extension method is even better (or a nice addition). Great, thank you!

**Comment by YevgeniyShunevych** [comment]
And it's done: #482.

**Comment by Piedone** [comment]
Thank you!
