### ISSUE TITLE
[question] two drivers are being triggered in one test

### ISSUE THREAD

**Issue by Ninelya** [atata-framework/atata#325]
Hi :)

So, I'm following your guide for multibrowser configuration, with the only change - i need to decide which browser to use during runtime, so i pass it via environment variable. 

Expectation: to have one browser open per test.

Problem is: when i run this, and define, say, firefox as my desired driver, first i get default browser opened, the one that's defined last in GlobalConfiguration (in my case it's chrome). At the end of RunBeforeAnyTests() method ChromeDriver is started, browser window is opened. Then, when BaseSetUp() is executed, firefox opens and test goes as expected. In the end firefox is properly closed, but chromedriver.exe process is still running until killed in Task manager. If I close Chrome during test execution, test fails. 

Questions: what do i do wrong and is it expected behavior?

My code looks like this:

```
[SetUpFixture]
public class SetUpFixture
{
    [OneTimeSetUp]
    public void RunBeforeAnyTests()
    {
        List<string> chromeArgumentsList = new List<string>()
        {
            "--enable-features=NetworkService,NetworkServiceInProcess",
            "--start-maximized"
        };
 
        EdgeOptions edgeOptions = new EdgeOptions
        {
            StartPage = AppSettings.Configuration.BaseUrl,
            PageLoadStrategy = PageLoadStrategy.Eager
        };

        AtataContext.GlobalConfiguration
            .UseEdge()
                .WithDriverPath(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location))
                .WithOptions(edgeOptions)

            .UseFirefox()
                .WithLocalDriverPath()

            .UseChrome()
                .WithFixOfCommandExecutionDelay()
                .WithLocalDriverPath()
                .WithArguments(chromeArgumentsList.ToArray())

            .UseBaseUrl(AppSettings.Configuration.BaseUrl)
            .UseBaseRetryTimeout(new TimeSpan(0, 0, 10))
            .UseNUnitTestName()
            .AddNUnitTestContextLogging()
            .AddScreenshotFileSaving()
            .LogNUnitError()
            .TakeScreenshotOnNUnitError()
            .Build();
    }
}

[TestFixture]
public class Test
{
	[SetUp]
	public void BaseSetUp()
	{
	   AtataContext.Configure().
					UseDriver($"{environment_variable_value}").
					Build();
	}
        [TearDown]
        public void BaseTearDown()
        {
            AtataContext.Current?.CleanUp();
        }
}
```

**Comment by YevgeniyShunevych** [comment]
Hey,

Just remove last line of `RunBeforeAnyTests` method. `GlobalConfiguration` should not be built, just configured.

**Comment by Ninelya** [comment]
Thank you very much :) that helped.
