### ISSUE TITLE
.NET Core 3.0

### ISSUE THREAD

**Issue by mzhukovs** [atata-framework/atata#326]
Plans to support .NET Core 3.0 anytime soon?

**Comment by YevgeniyShunevych** [comment]
It is supported. When you use .NET Core 3.0 for the test project and add Atata package it will use .NET Standard 2.0 version of Atata which is compatible with .NET Core 3.0. I've just created [sample solution for .NET Core 3.0](https://github.com/atata-framework/atata-samples/tree/master/NetCore3.NUnit) which you can check out.

Let us know if you get some issues using .NET Core 3.0.

**Comment by mzhukovs** [comment]
@YevgeniyShunevych  awesome, I'll give it a try on Sunday.  Thanks for the response and this really great library.

**Comment by YevgeniyShunevych** [comment]
Welcome and thanks.
