### ISSUE TITLE
[Question] About custom headers

### ISSUE THREAD

**Issue by cwhsu1984** [atata-framework/atata#337]
How do we setup custom header for chrome? I try to do it like the following, and does not seem to work.
```
AtataContext.GlobalConfiguration.
                UseChrome().
                    WithArguments("start-maximized", "X-Forwarded-For=1.2.3.4")
```

Are we able to do that? Or do we need to use extensions with Atata?
How do we use extensions with atata?

**Comment by cwhsu1984** [comment]
@YevgeniyShunevych Can you provide a direction for doing this? 
I need to test web site for multilingual and it detects the user ip, and this is a very usual case when using selenium.

**Comment by YevgeniyShunevych** [comment]
I didn't try `X-Forwarded-For` or something similar for WebDriver and Atata. Can you please provide an example of how to configure that by using pure WebDriver? I will be able to reflect that to Atata configuration.

**Comment by cwhsu1984** [comment]
This code is not completed yet as it get blocked when going to extension page, but it shows you what I'm trying to do.

```
using System.IO;
using OpenQA.Selenium.Chrome;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var options = new ChromeOptions();
            options.AddExtension(Path.GetFullPath(@"D:\workspaces\local\chromedriver_win32\modHeader.crx"));

            var driver = new ChromeDriver("D:\\workspaces\\local\\chromedriver_win32\\", options);

            driver.Navigate().GoToUrl("chrome-extension://idgpnmonknjnojddfkpgkljpfnnfcklj/icon.png");
            
            driver.ExecuteScript(
                "localStorage.setItem('profiles', JSON.stringify([{                " +
                "  title: 'Selenium', hideComment: true, appendMode: '',           " +
                "  headers: [                                                      " +
                "    {enabled: true, name: 'X-Forwarded-For', value: '223.24.189.66', comment: ''}, " +
                "  ],                                                              " +
                "  respHeaders: [],                                                " +
                "  filters: []                                                     " +
                "}]));"
                );
            
            driver.Navigate().GoToUrl("https://example.com/");
        }
    }
}
```

**Comment by cwhsu1984** [comment]
Just sharing my experience on using ModHeader to do add custom header. 
I finally able to use extension to add custom header as below
```
using System.IO;
using OpenQA.Selenium.Chrome;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var options = new ChromeOptions();
            options.AddExtension(Path.GetFullPath(@"D:\workspaces\local\chromedriver_win32\modHeader.crx"));

            var driver = new ChromeDriver("D:\\workspaces\\local\\chromedriver_win32\\", options);

            // https://github.com/bewisse/modheader_selenium
            // follow the instruction to use web api to add header
            driver.Navigate().GoToUrl("https://bewisse.com/add?Test1=1&Test2=2&X-Forwarded-For=223.24.189.66");
            driver.Navigate().GoToUrl("https://www.google.com");
        }
    }
}
```
 
However, my ultimate goal is to do this from docker, which then encounter another issue.
**The chrome driver currently is not supported extension in headless chrome** as discussed in the following links.

https://stackoverflow.com/questions/45372066/is-it-possible-to-run-google-chrome-in-headless-mode-with-extensions 
https://github.com/puppeteer/puppeteer/issues/659

So to achieve my goal, another way is to try to bring up a proxy server and add the customer header from proxy server, but it's not related to atata anymore.
