### ISSUE TITLE
Is it possible to use FindBy with data from external resource (JSON, Resources.resx, etc.)

### ISSUE THREAD

**Issue by alex-gagnon-firebrand** [atata-framework/atata#339]
Hello,

I am testing an application where I would ideally like to contain all my Id's, CSS selectors, etc. and then load them into the page objects FindBy. The reason for this being that I run these tests across multiple builds and databases that may have minor discrepancies in say, an Id field, but in the end is the same application.

current example:
```
// DB-1 id="id_in_div_3"
// DB-2 id="id_in_div_4"
[FindById("id_in_div_3")]
public Button<_> MyButton { get; private set; }
```

desired example:
```
[FindById(SomeIdNameFromFileOrResource)]
public Button<_> MyButton { get; private set; }
```

I may be trying to go about this the wrong way, but is this possible?

**Comment by YevgeniyShunevych** [comment]
Hey,

With Atata you can do it this way:

```cs
// [SomeOtherCommonAttributes...]
public Button<_> MyButton =>
        Controls.Resolve<Button<_>>(nameof(MyButton), () => new[] { new FindByIdAttribute(Resources.SomeIdNameFromFileOrResource) });
```

**Comment by YevgeniyShunevych** [comment]
There is also an "exotic" way of marking page object properties with attributes depending on the environment, using preprocessor directives.

```cs
#if ENV1
        [FindById("id-for-env-1")]
#elif ENV2
        [FindById("id-for-env-2")]
#else
        [FindById("id-regular")]
#endif
        public Button<_> MyButton { get; private set; }
```

This approach can also be used, but when there is not a lot of such different locator places, as it can become a mess.

**Comment by alex-gagnon-firebrand** [comment]
Awesome, I'll give this a try! 

I have another issue that I thought I resolved, but ended up finding another issue along with it. I have a Custom Select that finds the select's preceding sibling (which should be input) and sets the value there rather than the select field.
Initial code to set the value to input in 

```
<div>
<input id="the-value-is-set-on-me" />
<select id="i-get-clicked-and-become-hidden"></select>
</div>
```

```using Atata;

namespace My.WebPages
{
    /// <summary>
    /// Find by the <select> element and update the sibling <input>.
    /// </summary>
    /// <typeparam name="TOwner"></typeparam>
    [FindSettings(Visibility = Visibility.Any)]
    public class CustomSelect<TOwner> : Select<TOwner>
        where TOwner : PageObject<TOwner>
    {
        [FindFirst(OuterXPath = "preceding-sibling::", Visibility = Visibility.Any)]  // Issue is here I believe.
        [TraceLog]
        [PressTab]
        [WaitForOverlay]
        private TextInput<TOwner> AssociatedInput { get; set; }

        protected override void SetValue(string value)
        {
            Click().Wait(10);  // Click on <select> element.
            AssociatedInput.Set(value);
        }
    }
}
```


Current issue is that there are some locations that are similar to the above, but have additional siblings

```
<div>
<span>I'm an evil span preventing you from setting the input</span>
<input id="the-value-is-set-on-me" />
<select id="i-get-clicked-and-become-hidden"></select>
</div>
```

I did try `FindLast` - but this didn't work for me. I tried `FindByXPath` - still no luck. I tried a few other's and haven't quite figured out what i am missing. Perhaps this issue is not even what I suspect it is (that it the value is trying to be set to the <span> element. 

Error
`ElementNotInteractable`

**Comment by YevgeniyShunevych** [comment]
If you get `ElementNotInteractable` exception then that input might not be actually visible at that point, or visible but overlapped by another element. Ensure that it gets visible. Hard to say the reason 100%. Maybe you need to click that overlapping span. You need to investigate the changes of HTML during the clicks on that drop-down. Also detect (check logs) at what step an error is thrown, when you click the select or when try to set the value to input.

**Comment by alex-gagnon-firebrand** [comment]
I can confirm that the element is visible. In my custom select I added 

```
AssociatedInput.Should.BeVisible();
AssociatedInput.Attributes.Id.Should.Equal("the-span-id") // fails
AssociatedInput.Attributes.Id.Should.Equal("the-value-is-set-on-me") // passes

```
I notice that when the site is launched via the web driver, that I cannot manually set the input field. I can type, but when I press tab or enter, it just reverts to the original value.

**Comment by YevgeniyShunevych** [comment]
I am closing this issue as it is quite old. Hope you solved that problem.
