### ISSUE TITLE
Is it possible to use Atata with another test engine?

### ISSUE THREAD

**Issue by jkarurosu** [atata-framework/atata#340]
Hello 

I'm wondering if it is possible to use another test engine with Atata such as MSTest unit. If so it could be possible to use multi-browser capabilities and parallel execution?

**Comment by YevgeniyShunevych** [comment]
Yes, MSTest, as well as NUnit or XUnit, can be used with Atata. Check out [MSTest Atata sample](https://github.com/atata-framework/atata-samples/tree/master/MSTest). Here is also helpful article [MSTest v2: Execute tests in parallel](https://www.meziantou.net/mstest-v2-execute-tests-in-parallel.htm).

**Comment by 188867052** [comment]
We must change the source code to surport the XUnit Now!

**Comment by YevgeniyShunevych** [comment]
As you wish. Here is also the [sample project for Xunit](https://github.com/atata-framework/atata-samples/tree/master/Xunit).
