### ISSUE TITLE
Dynamic set ControlDefinition attribute

### ISSUE THREAD

**Issue by siquylee** [atata-framework/atata#342]
```
[ControlDefinition("div", ContainingClass = "m-article-card", ComponentTypeName = "iTownpageItem")]
public class iTownpageItem : Control<_>
    {
...
    }

```

Could you please tell how I can set the value of attribute ControlDefinition at the runtime?

**Comment by YevgeniyShunevych** [comment]
Unfortunately `ControlDefinition` can not be set dynamically for now. Probably we can add such a possibility in the future.

Anyway, why do you want to make it dynamic? Maybe we can solve your issue in a different way.

**Comment by siquylee** [comment]
The layout of web element can be changed in the future so I move the hard code values such as xpath values to JSON config. I'm new to Atata so I'm not sure how to define custom control.

**Comment by goblinmaks** [comment]
> Unfortunately `ControlDefinition` can not be set dynamically for now. Probably we can add such a possibility in the future.
> 
> Anyway, why do you want to make it dynamic? Maybe we can solve your issue in a different way.

![image](https://user-images.githubusercontent.com/1436234/74347488-d5d4c100-4db9-11ea-84e0-5697b3e23097.png)

How I can click by element with dynamically defined language ? 

`` 
        public void GivenIHaveOpenMainPage()
        {
            Go.To<MainPage>();
            On<HeaderLanguageDropDown<MainPage>>().LanguageButton("en").Click();
        }
``

**Comment by YevgeniyShunevych** [comment]
For language drop-down `LanguageButton` method to choose option by `data-langid` attribute can be implemented this way :

```cs
public Link<TOwner> LanguageButton(string languageId)
{
    return Controls.CreateLink<TOwner>(languageId, new FindByAttributeAttribute("data-langid", languageId));
}
```

**Comment by goblinmaks** [comment]
Works as expected. 
Please close this question.
