### ISSUE TITLE
Create multiple web driver instance in same process

### ISSUE THREAD

**Issue by siquylee** [atata-framework/atata#349]
It's difficult to handle multiple tab/window in one web driver instance in Selenium/Atata. I have an idea to create each web driver instance for each window/url and process in parallel. Is that possible for Atata? Do you have an example to implement that idea?

**Comment by YevgeniyShunevych** [comment]
A late response, but anyway here is the sample: [Atata Samples / Multiple Browsers in Test](https://github.com/atata-framework/atata-samples/tree/master/MultipleBrowsersInTest).
