### ISSUE TITLE
[WaitForJQueryAjax] is not started when select option from Select control

### ISSUE THREAD

**Issue by goblinmaks** [atata-framework/atata#352]
Page Object
![image](https://user-images.githubusercontent.com/1436234/77074923-36c76880-69fa-11ea-8164-24cbf9f95912.png)

Executed Method 
![image](https://user-images.githubusercontent.com/1436234/77075520-219f0980-69fb-11ea-9f59-f67977b01707.png)

Execution log
![image](https://user-images.githubusercontent.com/1436234/77075071-73935f80-69fa-11ea-9eca-5affb6dc5315.png)

**Comment by YevgeniyShunevych** [comment]
It's some kind of a bug or missing functionality. Thanks for informing.

Triggers with `AppliesTo = TriggerScope.Children` declared at the property level does not apply to control's children. Currently, it works only for triggers declared at the class level. This is the thing that should be improved in Atata.

Below is the temporary workaround:

```cs
[FindByName("countrySelector")]
[WaitForJQueryAjax(TriggerEvents.AfterSet)]
public Select<_> CountrySelectorDropDown { get; private set; }

protected override void OnInitCompleted()
{
    base.OnInitCompleted();

    TextSelect.Options.Metadata.Push(new WaitForJQueryAjaxAttribute(TriggerEvents.AfterClick));
}
```

Let me know if this workaround works for you.
