### ISSUE TITLE
Add AtataContextModeOfCurrent enum with ThreadStatic, Static and AsyncLocal values

### ISSUE THREAD

**Issue by YevgeniyShunevych** [atata-framework/atata#363]
Add `AtataContextModeOfCurrent` enum with `ThreadStatic`, `Static` and `AsyncLocal` values. It defines the modes of `AtataContext.Current` property.

Add property to `AtataContext`:

```cs
public static AtataContextModeOfCurrent ModeOfCurrent { get; set; }
```

Existing `IsThreadStatic` property of `AtataContext` becomes obsolete as `ModeOfCurrent` is a new recommended option that provides additional `AsyncLocal` mode.

## Note

`AsyncLocal` value is available to use only in .NET 4.6 and .NET Standard 2.0 versions of 
Atata. It is not available for .NET 4.0 and .NET 4.5 versions.

## Usage

It is recommended to set `AtataContext.ModeOfCurrent` in global setup method.

```cs
[SetUpFixture]
public class SetUpFixture
{
    [OneTimeSetUp]
    public void GlobalSetUp()
    {
        AtataContext.ModeOfCurrent = AtataContextModeOfCurrent.AsyncLocal;
    }
}
```

**Comment by Piedone** [comment]
I just wanted to add that how you document these things is exemplar. Thank you!
