### ISSUE TITLE
AtataContext.ModeOfCurrent needs to be set before building AtataContext

### ISSUE THREAD

**Issue by Piedone** [atata-framework/atata#364]
A small issue with 1.5. If I run

```
AtataContext.Configure().UseDriver(new ChromeDriver(".")) ... Build();
```

before

```
AtataContext.ModeOfCurrent = AtataContextModeOfCurrent.AsyncLocal;
```

then I get:

> System.InvalidOperationException
>   HResult=0x80131509
>   Message=Cannot build AtataContext as no driver is specified. Use one of "Use*" methods to specify the driver to use, e.g.: AtataContext.Configure().UseChrome().Build();
>   Source=Atata
>   StackTrace:
>    at Atata.AtataContextBuilder.ValidateBuildingContextBeforeBuild()
>    at Atata.AtataContextBuilder.Build()
>    at Atata.Go.CheckAtataContext()
>    at Atata.Go.To[T](T pageObject, GoOptions options)
>    at Atata.Go.To[T](T pageObject, String url, Boolean navigate, Boolean temporarily)

However, the driver is specified.

Simply moving the line with `ModeOfCurrent` before `AtataContext.Configure()` the error goes ways.

**Comment by Piedone** [comment]
Hmm, thinking about it, I'm not sure the new `AsyncLocal` `ModeOfCurrent` will actually work as I expect.

It seems to me that this won't work as `AtataContext.Current` will be `null`:

```
async Task BuildAtataContext()
{
    AtataContext.Configure()...
}

await BuildAtataContext();

// This throws the exception.
Go.To<Page>()...
```

And after all of such `async` context switches it'll be `null` again.

So I still think what I've suggested under https://github.com/atata-framework/atata/issues/317#issuecomment-616328119: All of these issues would go away if we could just supply optionally `AtataContext` to Atata methods like `Go`. There they wouldn`t need to rely on `AtataContext.Current7.

**Comment by YevgeniyShunevych** [comment]
I agree with that. I also want to decouple a lot of things out of `AtataContext.Current`, and provide easy API for using several contexts (browsers) in the scope of a single test. Not an easy story to implement, but yeah.

Anyway, if you describe the scenario you want to achieve with `AtataContext`, we might find some solution with the current version of Atata. `AtataContext.Current` is settable, so we can put there another value we need at any time.

**Comment by Piedone** [comment]
Yes, that's what I'm doing actually, setting `AtataContext.Current` before I'm using Atata methods that depend on it.

My use-case is that I'm starting up an [Orchard Core](https://www.orchardcore.net/) app for UI tests with dotnet.exe, creating an Atata context, and doing some async operations during this (primarily file IO). All in all my test initialization logic utilizes async a lot. This messes with `AtataContext.Current`.
