### ISSUE TITLE
AllowAutoRedirect functionality

### ISSUE THREAD

**Issue by MonzT** [atata-framework/atata#368]
Hi there
I've gone through the documentation and can't seem to find this anywhere. 

Looking for a way to automatically follow a redirect if there is one. 
Reference: https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest.allowautoredirect?view=netcore-3.1

**Comment by MonzT** [comment]
Basically, if I navigate to a page, and I receive a 3xx error, I'd like for the navigation to be retried with the new location.

**Comment by YevgeniyShunevych** [comment]
I thought browser with WebDriver should do it by default. In what browser it happens for you? And what do you see in browser in case of 3xx error?

**Comment by MonzT** [comment]
Running locally it works, but once in a CI pipeline (Gitlab, Docker, Kubernetes on linux), the redirect doesn't happen. Using Selenium.ChromeDriver nuget package.

It's running headless in the pipeline so don't really see much. Will see if I can get a screenshot at point of failure.

**Comment by YevgeniyShunevych** [comment]
I can see that this is common headless Chrome issue. You can google "chromedriver headless redirect" and try some of solutions that people recommend to try, like adding "--ignore-certificate-errors" or "--user-agent=Chrome/77" Chrome arguments.

**Comment by MonzT** [comment]
Awesome, thanks. I will try those
