### ISSUE TITLE
please add support for SauceLabs

### ISSUE THREAD

**Issue by iflanagan** [atata-framework/atata#374]
we need to add the sauce user and access key via desired caps but its not working with atata now

**Comment by iflanagan** [comment]
need the ability to pass in a sauce user and access key we tried doing it on ChromeOptions and before using the With but both failed to work.

AtataContext.GlobalConfiguration.UseRemoteDriver().

             WithAlias("chrome_remote").

             WithRemoteAddress("https://ondemand.us-west-1.saucelabs.com:443").

             WithOptions(new OpenQA.Selenium.Chrome.ChromeOptions()).username("test").UseBaseUrl(ConfigurationManager.AppSettings["BaseTestUrl"]).

                AddNUnitTestContextLogging().

                LogNUnitError();

----------In regular .NET you would do the following below-----------------------

* DesiredCapabilities capabilities = new DesiredCapabilities();

            //set your user name and access key to run tests in Sauce

            capabilities.SetCapability("username", sauceUserName);

            //set your sauce labs access key

            capabilities.SetCapability("accessKey", sauceAccessKey);

            //set browser to Safari

            capabilities.SetCapability("browserName", "Chrome");

            //set operating system to Windows version 10

            capabilities.SetCapability("platform", "windows 10");

            //set the browser version 

            capabilities.SetCapability("version", "latest");

            //set your test case name so that it shows up in Sauce Labs

            capabilities.SetCapability("name", TestContext.CurrentContext.Test.Name);

            //create a new Remote driver that will allow your test to send

            //commands to the Sauce Labs grid so that Sauce can execute your tests

            _driverAlias = new RemoteWebDriver(new Uri("https://ondemand.us-west-1.saucelabs.com:443"),

capabilities, TimeSpan.FromSeconds(600));

            //navigate to the url of the Sauce Labs Sample app

            _driver.Navigate().GoToUrl("https://www.saucedemo.com");

**Comment by YevgeniyShunevych** [comment]
Check out newer Sauce configuration approach here: https://wiki.saucelabs.com/display/DOCS/W3C+Capabilities+Support

Here is it for Atata:

```cs
var chromeOptions = new ChromeOptions
{
    BrowserVersion = "latest",
    PlatformName = "Windows 10",
    UseSpecCompliantProtocol = true
};

var sauceOptions = new Dictionary<string, object>
{
    ["username"] = _sauceUsername,
    ["accessKey"] = _sauceAccessKey,
    ["name"] = TestContext.CurrentContext.Test.Name
};

chromeOptions.AddAdditionalCapability("sauce:options", sauceOptions, true);

AtataContext.GlobalConfiguration.
    UseRemoteDriver().
        WithAlias("chrome_remote").
        WithRemoteAddress("https://ondemand.us-west-1.saucelabs.com:443").
        WithOptions(chromeOptions);
```
