### ISSUE TITLE
Resolve an element without attribute

### ISSUE THREAD

**Issue by wmolyneux** [atata-framework/atata#38]
Given a table with three columns (Time, Id, Message) I have created a Table inside my page object model which contains the TableHeaders and the TableRows to locate these static columns in my table.

I then had an issue where if the columns were to appear in a different order than I would use the FindByXPath attribute on the TableRow to look at the index of the column that ID occurs in use that index whilst locating the cell for ID in the table row.

However my table has the option to add extra columns based on user data in the system. There is not a way to know what the user data is and therefore I was planning to add a function onto the TableRow for retrieving the custom property by name. Then the function can use the same XPath as above to take the string property name and look for a header matching that property name, and then use the index of the header to find which cell in the row contains the value for that data.

Is there a way to resolve elements not using attributes?

I have tried using AtataContext.Current.Driver.FindElementByXPath however this returns an IWebElement instead of a the desired Text<_> object and I cannot seem to cast or create one,

Thanks

**Comment by YevgeniyShunevych** [comment]
There is a possibility to create controls dynamically. Unfortunately, it is not documented yet. In scope of component you can call `Controls.Create("some name")` or `Controls.Create("some name", [some attributes])`.

For your case you can implement it this way:
```cs
public class SampleRow : TableRow<_>
{
    // If you need controls of different types.
    public TControl Get<TControl>(string columnName)
        where TControl : Control<_>
    {
        return Controls.Create<TControl>(columnName, new FindByXPathAttribute("some xpath"));
    }

    // If you need just Text<_> controls.
    public Text<_> Get(string columnName)
    {
        return Controls.Create<Text<_>>(columnName, new FindByXPathAttribute("some xpath"));
    }

    // Or even using indexer.
    public Text<_> this[string columnName]
    {
        get { return Controls.Create<Text<_>>(columnName, new FindByXPathAttribute("some xpath")); }
    }
}
```

Also you can use `FindByColumnHeaderAttribute` to find row cells:
```cs
[FindByColumnHeader(TermMatch.Contains)]
public Text<_> Message { get; private set; }
```

**Comment by wmolyneux** [comment]
That seems great, thanks for the quick reply.

**Comment by YevgeniyShunevych** [comment]
Welcome.

**Comment by wmolyneux** [comment]
On the topic of locating elements using XPath:
Given a table:
`<table id="products">
    <thead>
        <tr>
            <th><p>Name</p></th>
            <th><p>Amount</p></th>
            <th><p>Actions</p></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Item 1</td>
            <td>5</td>
            <td><button>Delete</button></td>
        </tr>
        <tr>
            <td>Item 2</td>
            <td>10</td>
            <td><button>Delete</button></td>
        </tr>
    </tbody>
</table>`

When I create the TableHeader<_> class and decorate a property called headerName with the following:
`[FindByXPath("//p")]`

I was expecting the XPath to be executed relative to each header therefore getting a list of headers off the table and calling .headerName on each would yield different results.

Instead I seem to only ever get the first paragraph tag in the table instead. yielding three results with the first paragraph tag in each. 

The documentation seems a little sparse on XPaths that are not very specific such as "//th/p[@id="id"]"

Thanks

**Comment by YevgeniyShunevych** [comment]
You need to use such XPath: ".//p" or just "p" (".//" prepends by default). This way it will find element in scope of current control. "//p" finds elements in whole document from the beginning.

**Comment by wmolyneux** [comment]
Ah that makes more sense. In the past whilst using selenium I have executed XPath on a webelement which seemed to find it below the element the xpath is being executed on.

I am trying to determine whether Atata suits my Automation testing needs as opposed to building my own framework on top of Selenium like I have done in the past. So far seems great, just ensuring that the more complicated scenarios are do-able before commiting and encountering problems furhter down the line.

Thanks again for you're help.

**Comment by YevgeniyShunevych** [comment]
No problem. Sure, try different complex scenarios. Post questions/issues if you will have some. I periodically  add features and enhancements for the parts of framework where there is a gap.
