### ISSUE TITLE
Add drag and drop support

### ISSUE THREAD

**Issue by wmolyneux** [atata-framework/atata#39]
Selenium provides a mechanism for allowing actions to be performed such as drag and drop with certain key presses. This allows for the automation of actions such as shift drag and drop or ctrl drag and drop. 

It would be nice to be able to drag an element to another element and drop it. Perhaps also allow for a way to say whereabouts on the second object you would like to drop the item?

I always find drag and drop a very annoying feature to implement using Selenium and having 'Atata' do it nicely would be a huge benefit!

**Comment by YevgeniyShunevych** [comment]
I see your issue. For now, you can take a look at issue #25, in which is described how it can be implemented using WebDriver actions. I also think how to provide similar Atata API for easy use.

**Comment by YevgeniyShunevych** [comment]
Drag and drop functionality added to recently released [Atata v0.13.0](https://atata-framework.github.io/blog/2017/06/27/atata-0.13.0-released/#drag-and-drop).
