### ISSUE TITLE
support for dynamic XPath which will be configured as per the test case requirement

### ISSUE THREAD

**Issue by akumar57** [atata-framework/atata#396]
Hi,

I have been trying 1 scenario and I am stuck completely. I have to generate a dynamic XPath with varying rows and fetch the text out of it and compare it with a string.(I have applied a filter and I have to validate text from each row)

for e.g. I am looking for something like this :  

 [FindByXPath("//*[@id='FilterRow']/tr{0}/td[1]")]    //here value for "tr" has to change 
  public TextInput<_> FilterTextbox { get; private set; }

///////
test class ==>

for (i=0;i <10;i++)
{
Assert.True(TextInput[i] == "ExpectedText");
}

I am also new to C# +NUnit ...So I am unable to crack it .

**Comment by YevgeniyShunevych** [comment]
For this kind of actions there are special components:
- [Table](https://atata.io/components/#table)
- [ItemsControl](https://atata.io/components/#itemscontrol)
- [ControlList](https://atata.io/components/#controllist)

Try to use one of them.

**Comment by akumar57** [comment]
Hi,

Thank you for the reply. But, unfortunately, above 3 items does not solves my problem. They all mainly focus on comparing with some fixed string for e.g. below

Table.Rows[x => x.Content == "**some content**"].Click();

What if I want to dynamically prepare a string and make a comparsion with "x.content" like ["some content + {0}"] where {0) is replaced with 1,2,3 etc. inside a loop. 

But still I am managing by escaping such assertions and overall you have done a great job. Congrats

Regards,
Anand Kumar

**Comment by YevgeniyShunevych** [comment]
You are welcome.
