### ISSUE TITLE
Table Rows iteration is adding an extra " within string

### ISSUE THREAD

**Issue by brandyndauch** [atata-framework/atata#460]
Hello Yevgeniy,

I'm dealing with a table rows iteration issue. It seems as though Atata may be compiling with an extra `"` character to my search. 

My code: `printingSummaryPage.Specifications.ComponentTable.Rows[row => row.Content == "Case"].Should.Exist();`

Stack Trace error:  `Wrong "Specifications" control's "Component" table's "Content == "Case"" row presence.`

Thank you in advance for your help,
-B

**Comment by YevgeniyShunevych** [comment]
I see you have closed it already. Yes, there is no extra `"` character, this is just the way log wraps the predicate.
