### ISSUE TITLE
WithFixOfCommandExecutionDelay in Atata.json 

### ISSUE THREAD

**Issue by brandyndauch** [atata-framework/atata#479]
Hi Yevgeniy,

Was curious if it was possible to integrate WithFixOfCommandExecutionDelay in the default Atata.json file? If so, where within the file would I want to notate the method? I'm noticing some speed issues with my test as my repo grows. 

Thank you for the help!

Brandyn

**Comment by YevgeniyShunevych** [comment]
What `WithFixOfCommandExecutionDelay` method does, is sets `"127.0.0.1"` value instead of default `"localhost"` into `HostName` property of `DriverService` class.

You can do the same in JSON config file:

```json
{
  "driver": {
    "type": "chrome",
    "service": {
      "hostName": "127.0.0.1"
    }
  }
}
```

**Comment by brandyndauch** [comment]
You're the best! That makes a lot of sense. 

Thank you!
-B

**Comment by YevgeniyShunevych** [comment]
You are welcome. I've also [updated the docs](https://atata.io/getting-started/#dot-net-core-configuration) with that.
