### ISSUE TITLE
Ability to save log event timestamps in UTC or a custom time zone

### ISSUE THREAD

**Issue by Piedone** [atata-framework/atata#483]
Currently, log events [are always saved](https://github.com/atata-framework/atata/blob/a8553b608f5ad84ca1e13d6ad1e3b0a133ea691d/src/Atata/Logging/LogEventInfo.cs#L12) with `DateTime.Now` which will use the machine's time zone. Instead, I suggest either switch this to UTC so the times are always consistent regardless of where the tests are executed or make this configurable.

**Comment by YevgeniyShunevych** [comment]
It sounds good, @Piedone. I don't want to change the current behavior, in respect to backward compatibility. But I can add a configuration property to set the `TimeZoneInfo` value or its `Id` value. The default will be `TimeZoneInfo.Local`. Then you'll be able to set it with `TimeZoneInfo.Utc`.

**Comment by Piedone** [comment]
Sounds perfect!

**Comment by YevgeniyShunevych** [comment]
Hey @Piedone. This feature is implemented be #498. It's going to be release with Atata v1.11.0 next week.

**Comment by Piedone** [comment]
Great, thank you!
