### ISSUE TITLE
Not able to disable "Ask where to save each file before downloading" option in chrome

### ISSUE THREAD

**Issue by Kamalika7** [atata-framework/atata#488]
Tried below mentioned code but it didn't work

 AtataContext.GlobalConfiguration                
                .UseChrome()                
                 .WithOptions(opt => opt.AddUserProfilePreference("download.default_directory", @"C:\Temp"))
                 .WithOptions(opt => opt.AddUserProfilePreference("download.prompt_for_download", false))

still the prompt is appearing where it is asking to choose the download path.
Need solution to stop the the download prompt from appearing

**Comment by YevgeniyShunevych** [comment]
I have just tested with these options in recent Chrome v90 with latest ChromeDriver and it is OK.

May it be that you put this `GlobalConfiguration` initialization logic in the wrong place? Please, ensure that this code is executed before the test's `AtataContext` is created and test's `AtataContext` is not resetting this options. If you can, please share all the blocks of Atata initialization code.

**Comment by YevgeniyShunevych** [comment]
@Kamalika7, have you solved that?

**Comment by Kamalika7** [comment]
Hi,

I found out that the code was not working due to policies set by the
organization. I used AutoIt to handle the windows prompt to download the
file.
Thank you very much for asking back on the status. Really appreciate your
support.

Thanks,
Kamalika

**Comment by YevgeniyShunevych** [comment]
Sure, no problem. I am closing the issue then.
