### ISSUE TITLE
Is it possible to make an assertion for internals of the <script>?

### ISSUE THREAD

**Issue by dariusz-wozniak** [atata-framework/atata#507]
Hi!

Is it possible to make an assertion for the internals of the <script>? Let's say, there's a JSON structured data within one of the <script> element on a page.

**Comment by YevgeniyShunevych** [comment]
I can see an option to get HTML page source and then using `Regex` try to find the needed script part.

```cs
string html = pageObject.PageSource.Value;
// Process html...
```

**Comment by dariusz-wozniak** [comment]
Wonderful, thank you @YevgeniyShunevych.

**Comment by YevgeniyShunevych** [comment]
You are welcome, @dariusz-wozniak.
