### ISSUE TITLE
Reporting to Extent Reports: Test is succesful even if it failed

### ISSUE THREAD

**Issue by dariusz-wozniak** [atata-framework/atata#508]
Hi!

I've used Extent Reports samples ([link](https://atata.io/tutorials/reporting-to-extentreports/)) for reporting, but even if test fails and `AtataException` is thrown, it is being reported as a succesful assertion and successful test.

Please note I'm using `AggregateAssert`.

Assert message:

```
< Assert: "Privacy Policy" link enabled state should be false (11.443s) >> Atata.AssertionException: Wrong "Privacy Policy" link enabled state...
```

![image](https://user-images.githubusercontent.com/5969160/123813735-6fd8d300-d8f5-11eb-9a28-ca296a6b2e08.png)

![image](https://user-images.githubusercontent.com/5969160/123813873-88e18400-d8f5-11eb-8f4b-8b1167095458.png)

Dashboard:

![image](https://user-images.githubusercontent.com/5969160/123813807-7d8e5880-d8f5-11eb-88b2-1c0d60bf7c8f.png)

Can you please suggest what to do in order to make test reported as a failed one?

Atata version: 1.11.2
ExtentReports version: 4.1.0

**Comment by YevgeniyShunevych** [comment]
Hi, I will take a look. Do you use NUnit (especially `UseAllNUnitFeatures()` or `LogNUnitError()` method of `AtataContextBuilder`) or other testing framework?

**Comment by YevgeniyShunevych** [comment]
I have added a fix to [ExtentLogConsumer.cs](https://github.com/atata-framework/atata-samples/blob/master/ExtentReports/AtataSamples.ExtentReports/Infrastructure/ExtentLogConsumer.cs) with [this commit change](https://github.com/atata-framework/atata-samples/commit/07d8e922b30e0165dacace35f2556647cc8f53ed). Please check whether it makes your assertion fail.

**Comment by dariusz-wozniak** [comment]
Thanks for the quick response!

I'm using MsTest in that case.

It still didn't fail test in Extent Reports, because `isEndOfVerificationLogSection` is false. However, I added one more if-statement to that code and it works properly:

```
case LogLevel.Info:
    bool isEndOfVerificationLogSection = !(eventInfo.SectionEnd as VerificationLogSection)?.Message.StartsWith("Wait") ?? false;

    if (isEndOfVerificationLogSection)
    {
        if (eventInfo.SectionEnd.Exception is null)
        {
            var lastLogLevel = ExtentContext.LastLogEventOfCurrentTest.Level;

            if (lastLogLevel != LogLevel.Error && lastLogLevel != LogLevel.Warn)
                return Status.Pass;
        }
        else
        {
            return Status.Fail;
        }
    }
    // new code
    if (eventInfo?.SectionEnd?.Exception != null)
    {
        return Status.Fail;
    }

    return Status.Info;
```
