### ISSUE TITLE
How to make custom assertions?

### ISSUE THREAD

**Issue by dariusz-wozniak** [atata-framework/atata#509]
Continuing the thread https://github.com/atata-framework/atata/issues/507 _Is it possible to make an assertion for internals of the <script>?_:

I'm getting custom `<script>` by HtmlAgilityPack and LINQ and I'm using FluentAssertions for assertions (assertion is on top of the string or the list), but the assertion code is outside the Atata flow.

What would be the best approach for keeping assertion close to test?

Now, it looks like (approach 1):

```
var script = Go.To<Pages.MainPage>().GetScript();
script.Should(/* ... FluentAssertion here */
```

I was thinking about something like (2):

```
Go.To<Pages.MainPage>()
     .Script // property with custom logic
     .ShouldSatisfy(() => { /* custom conditions */}, "Assertion message");
```

or (3):

```
Go.To<Pages.MainPage>()
     .Script() // extension with custom logic
     .ShouldSatisfy(() => { /* custom conditions */}, "Assertion message");
```

The second and the third approach seems to be more appropiate. How this could be achieved?

As a side note, I'm using MsTest in that context.

**Comment by YevgeniyShunevych** [comment]
Does your `GetScript()` method return a string?

**Comment by dariusz-wozniak** [comment]
Yes, `GetScript()` returns a string.

However, yet another method returns `List<string>`.

**Comment by YevgeniyShunevych** [comment]
OK. You can do something like this:

```cs
public class SomePage : Page<_>
{
    public DataProvider<string, _> SomeScript => GetOrCreateDataProvider("some script", GetScript);

    private string GetScript()
    {
        // TODO: Get script...
        return null;
    }
}
```

Then in the test:

```cs
Go.To<SomePage>()
    .SomeScript.Should.AtOnce.Satisfy(x => /* Do custom check here and return true/false */false, "be valid or whatever...");
```

**Comment by dariusz-wozniak** [comment]
Great, that works like a charm, thank you very much!

**Comment by YevgeniyShunevych** [comment]
You are welcome.
