### ISSUE TITLE
How to wait until page loads?

### ISSUE THREAD

**Issue by vadim-96** [atata-framework/atata#517]
Code:
`AdminLoginPage.LoginButton.ClickAndGo<AdminPage>();`
After clicking on LoginButton, AdminLoginPage can take a very long time to load, but the framework already goes to AdminPage without login, so a test fails.

In Selenium this problem is solved with one code line: `wait.until(document.readyState == "completed")`

**Comment by YevgeniyShunevych** [comment]
You just need to add `[WaitForDocumentReadyState]` attribute to the needed page object class.

**Comment by vadim-96** [comment]
Thanks, it works.
@YevgeniyShunevych could you please answer another question:
When I use the `[FindByXPath("//*[@id='save']/..")]` attribute, it turns into `(//*[@id='save']/..)/descendant-or-self::*"`, so how do I remove `descendant-or-self::*` from the query?

**Comment by YevgeniyShunevych** [comment]
Basically, you can't cut that part in `FindByXPath`.

But let's take a look at your XPath. You want to find an element with `id='save'` and then take it's parent. I would change the logic of finding to: find an element that has a child with `id='save'`. Almost the same, just a bit straightforward.

Now instead of:

```cs
[FindByXPath("//*[@id='save']/..")]
```

you can write it this way:

```cs
[FindByInnerXPath("child::*[@id='save']")]
```

The generated XPath should be cleaner for this case.

**Comment by vadim-96** [comment]
It works, thanks.
But I don't think that adding or changing selector is a good idea. If you wrote `//*[@id='save']` selector, it should be unchanged

**Comment by YevgeniyShunevych** [comment]
Sorry for a late response, @vadim-96. Regarding XPathes.

One of the basic ideas behind Atata is to get rid of traditional direct XPath and CSS locators as much as possible. In Atata we try to operate components (page objects and controls). Each control can and basically should have some `[ControlDefinition("some-xpath")]` that describes basic XPath of the control element. Basic XPath for a `Link` control is `"a"`, for example. This signifacantly narrows down the number of elements on the page that can match out further selector and guarantees that other kind of element will not be found. Then, for example, if we add `[FindById("some-id")]` selector to a `Link` property, the result XPath will be a combination of 2 parts: the logic of `[FindById]` (find some element with specific ID) and basic XPath. So it will be `".//*[@id='some-id']/descendant-or-self::a"`. Yes it could be shorter `.//a[@id='some-id']`. But `descendant-or-self` gives you additional ability to find a control not directly with specific ID, but also inside that element with ID. It is quite useful when there is no adequate identifiers on the needed element but there are some in the parent or grand-parent element.
