### ISSUE TITLE
How to find a label by attribute for?

### ISSUE THREAD

**Issue by gustavomoises** [atata-framework/atata#540]
Hi Atata Community,

I am trying to map a label that only has a FOR attribute like the example below:

`<span class="checkboxlist" id="example" data-umb="example"> 
       <input type="checkbox" class="" name="example" id="example_0" data-umb="example_0" value="Mango">
      <label for="example_0">
              Mango
        </label> 
       <input type="checkbox" class="" name="example" id="example_1" data-umb="example_1" value="Apple">    
       <label for="example_1">Apple</label>    
</span>`

I could map the checkbox( I am not using the example because it is autogenerated string, i.e. 778io-edf89juuu,  that can change from time to time):
`     [FindByValue(TermMatch.Contains, "Mango")]        public CheckBox<TOwner> Mango { get; private set; }        `

but  I only could map the label by index:
`[FindByIndex(3)]        public Label<TOwner> LabelMango { get; private set; }`

It is important to say that the checkbox id is equal to the for attribute of the label.

Is there any other mapping option? Like FindByForAttribute?

Besides, I would like to make it more generic using a control list of checkbox+label called Fruits. If I would like to check a specific checkbox fruit I would write:
`CurrentPage.Fruits.CheckFruit("Mango")`

**Comment by YevgeniyShunevych** [comment]
1. There is a generic `FindByAttributeAttribute` that you can use like `[FindByAttribute("for", "SOMEVALUE")]`.
1. Also you can find checkbox by associated label text:
   ```cs
   [FindByLabel(TermMatch.Contains, "Mango")] // Or even just [FindByLabel]
   public CheckBox<TOwner> Mango { get; private set; }
   ```
   It will find the label by text, get `for` attribute value and then find the checkbox by `id` that equals the value of label's `for`.
1. But as the easiest option here I see to use [CheckBoxList](https://atata.io/components/#checkboxlist) control. Check out it in docs, there is an example there.

Please, let me know if none of these approaches works for you.

**Comment by gustavomoises** [comment]
Thank you @YevgeniyShunevych.  I tried to implement the third option but it didn't work. The checkbox list currently supports only enum (with [Flags]) types. Unfortunately,  the option's value has space and parenthesis ("The Mango from Brazil ( Export Label)") that is not supported by enumeration. I tried to use Description but it didn't work:
`        public CheckBoxList<FruitOptions, TOwner> Fruits { get; private set; }` 


      `  [Flags]
        public enum FruitOptions
        {
            None = 0,         // C#7: 0b0000
            [Description("The Mango from Brazil (Export Label)")]
            Mango = 1,      // C#7: 0b0001
            [Description("Crispy Apple (Snow White Label)")]
            Apple = 1 << 1, // C#7: 0b0010
        }`

Do you have any other suggestion?

**Comment by YevgeniyShunevych** [comment]
It is probably not described in docs but it is possible by using `TermAttribute`:

```
[Flags]
public enum FruitOptions
{
    None = 0,         // C#7: 0b0000
    [Term("The Mango from Brazil (Export Label)")]
    Mango = 1,      // C#7: 0b0001
    [Term("Crispy Apple (Snow White Label)")]
    Apple = 1 << 1, // C#7: 0b0010
}
```

**Comment by gustavomoises** [comment]
@YevgeniyShunevych It worked. Thanks.

**Comment by YevgeniyShunevych** [comment]
Great. You're welcome.
