### ISSUE TITLE
How to define control in page object, which is missing until some action will be happend?

### ISSUE THREAD

**Issue by AngryTester95** [atata-framework/atata#541]
Hi!

I'm trying to define page object and on the page context menu is shown only after clicking by some button. So, my question is how to define this context menu in the page object class? I can't use **_Visibility.Hidden_**, because this control is just missing while button won't be clicked. And describle context menu as page objecy instead of control isn't a good idea.

Thanks in advance!

**Comment by YevgeniyShunevych** [comment]
Hey,

You can use `Visibility.Any` for it. And yes, context menu should be represented in a page object as a control.

If you need, you can share a part of the page object, so I can advice something in details.

**Comment by AngryTester95** [comment]
@YevgeniyShunevych  yes it works for me, thanks!

**Comment by YevgeniyShunevych** [comment]
You're welcome!
