### ISSUE TITLE
How to find specified control after page object initialization?

### ISSUE THREAD

**Issue by AngryTester95** [atata-framework/atata#544]
Hi!

Let's imagine, that some popup with different controls (based on external conditions) can be shown after doing some action (click on a button, for example).  Specify n properties with popups in page object isn't an good idea. And Create popup as page object as well, from my point of view.

**Comment by YevgeniyShunevych** [comment]
There is [PopupWindow](https://atata.io/components/#popupwindow) class that you can use as a base class for popup. You can check out [Handle Confirmation Popups](https://atata.io/tutorials/handle-confirmation-popups/) tutorial. The idea is similar there.

**Comment by YevgeniyShunevych** [comment]
@AngryTester95, did that help?

**Comment by AngryTester95** [comment]
@YevgeniyShunevych sorry for delay. Yes, it helped me. Thanks!

**Comment by YevgeniyShunevych** [comment]
Great! I will close this issue then.
