### ISSUE TITLE
WaitBy considering another Attribute like ng-click

### ISSUE THREAD

**Issue by gustavomoises** [atata-framework/atata#551]
Atata Team,

I would like to know if it is possible to implement a WaitBy considering other attributes, for instance, ng-click from Angular.

This is a classic WaitBy example considering a Class:
`
 [WaitForElement(WaitBy.Class, "button", Until.Visible, TriggerEvents.AfterClick, PresenceTimeout = 60)]
 public Button<_> ButtonA { get; private set; }
`

In my scenario,  the program has more than 1 element with the same class no ID, no name, same XPath and CSS. The only thing different is the ng-click.

**Comment by YevgeniyShunevych** [comment]
Hey. If I understood your issue correctly, you can try to wait by XPath:

```cs
[WaitForElement(WaitBy.XPath, "//*[@ng-click='SOMEVALUE']", Until.Visible, TriggerEvents.AfterClick, PresenceTimeout = 60)]
```

**Comment by YevgeniyShunevych** [comment]
Hey, @gustavomoises. Did that help?

**Comment by gustavomoises** [comment]
It worked. It did help.
Gustavo    On Friday, November 19, 2021, 01:12:19 AM MST, Yevgeniy Shunevych ***@***.***> wrote:  
 
 


Hey, @gustavomoises. Did that help?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YevgeniyShunevych** [comment]
Great. I will close this issue then.
