### ISSUE TITLE
Loading the AtataContext from file

### ISSUE THREAD

**Issue by roly445** [atata-framework/atata#56]
Hi I have just started to look at your framework as was wondering if there was a way to load the AtataContext from a config file?

**Comment by YevgeniyShunevych** [comment]
Hi,

Unfortunately, there is no built-in functionality for that currently. I plan to add it in a future version (JSON and/or App.config).

For now, you can take a look at [atata-framework/atata-sample-app-tests](https://github.com/atata-framework/atata-sample-app-tests) repository. There I read some settings for `AtataContext` from [App.config](https://github.com/atata-framework/atata-sample-app-tests/blob/master/src/AtataSampleApp.AutoTests/App.config) using [Config.cs](https://github.com/atata-framework/atata-sample-app-tests/blob/master/src/AtataSampleApp.AutoTests/Config.cs) class:
```cs
public static class Config
{
    public static string Url { get; } = ConfigurationManager.AppSettings[nameof(Url)];

    public static class Account
    {
        public static string Email { get; } = ConfigurationManager.AppSettings[nameof(Email)];

        public static string Password { get; } = ConfigurationManager.AppSettings[nameof(Password)];
    }
}
```

And then I use the settings in [UITestFixture.cs](https://github.com/atata-framework/atata-sample-app-tests/blob/master/src/AtataSampleApp.AutoTests/UITestFixture.cs).

**Comment by YevgeniyShunevych** [comment]
Check [atata-framework/atata-configuration-json](https://github.com/atata-framework/atata-configuration-json) repository for JSON configuration.
