### ISSUE TITLE
IWebDriver-using AtataContextBuilder.UseDriver()

### ISSUE THREAD

**Issue by Piedone** [atata-framework/atata#598]
The v4 Selenium changelog says:

>  Refactored .NET bindings class inheritance hierarchy. This breaks the
   assumption that all browser-specific driver (ChromeDriver, FirefoxDriver,
   EdgeDriver, etc.) are all subclasses of RemoteWebDriver. This is no longer
   the case. **The guidance for all users has always been to write your
   Selenium code using the IWebDriver interface**, rather than the concrete
   implementation classes.

See [here](https://github.com/SeleniumHQ/selenium/blob/trunk/dotnet/CHANGELOG#:~:text=Refactored%20.NET%20bindings,a%20breaking%20change.).

Thus, please add an `AtataContextBuilder.UseDriver()` overload that accepts an `IWebDriver`, not `RemoteWebDriver` (this can actually be an in-place replacement too, since `RemoteWebDriver` implements `IWebDriver`. I see thought that `RemoteWebDriver` permeates the library, starting with `IDriverFactory`, so this might be a substantial change.

**Comment by YevgeniyShunevych** [comment]
Right. This is going to happen in Atata v2, which will switch to WebDriver 4.

**Comment by Piedone** [comment]
When do you plan to release that?

**Comment by YevgeniyShunevych** [comment]
It is hard to say about the release date of complete Atata v2. But I'm going to release Beta 1 working on WebDriver 4 in a week or two.

**Comment by Piedone** [comment]
Awesome!

**Comment by Piedone** [comment]
Isn't this addressed with v2?

**Comment by Piedone** [comment]
Great! May I suggest closing this issue then?
