### ISSUE TITLE
Consider using GitHub auto-generated release notes

### ISSUE THREAD

**Issue by Piedone** [atata-framework/atata#661]
When you add a new release on GitHub you have an option to [auto-generate release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes). This is useful for users of your project because, at a glance, they'll see a list of merged PRs and a link to the delta between the current and the previous release (as well as it adds the list of contributors and emphasizes first-time contributors). It is naturally also easier than writing release notes by hand.

**Comment by YevgeniyShunevych** [comment]
Thanks, @Piedone. I will use this feature for future releases. I also added "Full Changelog" link to v2.0.0 release.

**Comment by Piedone** [comment]
Awesome, thanks!
