### ISSUE TITLE
Custom dropdown list

### ISSUE THREAD

**Issue by bughunterqa** [atata-framework/atata#673]
Could you please help me how can I create custom component for my dropdown (not Bootstrap and not standard Select). I need to just click the dropdown and find the element inside the element by text (or by any value)

Something like this:

`[FindByXPath("//p-dropdown[@optionlabel='countryName']")]`
`public CustomSelect<Country, _> CountryList { get; private set; }`

`Go.To<RegisterForm>().`
`       CountryList.Should.Equal(Country.None).`
`       CountryList.Set(Country.Ukraine);`

Please just a simple example

**Comment by YevgeniyShunevych** [comment]
You can take a look at these examples:
- https://github.com/atata-framework/atata-samples/tree/master/ExtJS
- https://github.com/atata-framework/atata-samples/tree/master/SalesforceLightning
- https://gist.github.com/YevgeniyShunevych/ec74f7ade13d3fdfde17e6a783e23d3e
- https://github.com/atata-framework/atata-kendoui/blob/main/src/Atata.KendoUI/KendoDropDownList%602.cs

**Comment by bughunterqa** [comment]
I still cannot find the inner elements(

**Comment by YevgeniyShunevych** [comment]
Yes, that's right. Great, that you solved that.
