### ISSUE TITLE
[FindItemByLabel] for RadioButtonList

### ISSUE THREAD

**Issue by bughunterqa** [atata-framework/atata#674]
How use this update https://github.com/atata-framework/atata/issues/114 ?
I've added the [FindItemByLabel] attribute to the RadioButtonList, but it's still searching for the Input tag :
![image](https://user-images.githubusercontent.com/68702481/192736034-46d8bab8-4988-4719-8608-0eec6b4c6ab3.png)
![image](https://user-images.githubusercontent.com/68702481/192737301-6ea650b0-ec9f-45fb-b879-27db52c4124e.png)

And i getting such error message: 
**OpenQA.Selenium.NoSuchElementException : Unable to locate element:**
**By: XPath ".//*[normalize-space(@name) = 'industry-role']/descendant-or-self::input[@type='radio'][@id='Broker']"**
![image](https://user-images.githubusercontent.com/68702481/192736743-a000f558-642b-47bd-be9a-367da4998c80.png)

FYI: i dont have the able to click on the input because of it isnt clickable

**Comment by YevgeniyShunevych** [comment]
Yes, it searches for the `input` tag to click it. But before that it finds a `label` to retrieve input's id. In trace log before exception you should see a line like this "Find element by XPath ".//label[normalize-space(.) = 'Broker']"".

I see another problem in your example. Inputs have "industryRoleId" name, not "industry-role". So you need to add `[FindByName("industryRoleId")]` attribute to `IndustryRole` property.

Regarding:
> FYI: i dont have the able to click on the input because of it isnt clickable

Try adding the `[ClicksUsingActions]` behavior attribute. It should help.

**Comment by bughunterqa** [comment]
Thank for u answer, [ClicksUsingActions] attribute didnt help but i found solve: 

1. Replacing [ControlDefinition("input[@type='radio']")]  to [ControlDefinition("label")]   
2. Adding [FindItemByRelativeElementContent("@for")]

**Comment by bughunterqa** [comment]
Another quick question: Can I use the components of a page without first going to that page? For example, I have a class with common elements, and I need to click on some button, how can I do this without using before:  **Go.To<CommonPage>().**

**Comment by YevgeniyShunevych** [comment]
In Atata no, there should be a single active page object activated with `Go.To`. But you can extract common controls for example to base page object class. Check out [Page Object Inheritance](https://atata.io/examples/page-object-inheritance/).

**Comment by bughunterqa** [comment]
@YevgeniyShunevych Thanks for the reply, just wanted to u know: Im in awe of your framework, thanks for what u do!
