### ISSUE TITLE
Add page snapshot functionality

### ISSUE THREAD

**Issue by YevgeniyShunevych** [atata-framework/atata#698]
A new functionality for taking a page snapshot, which can be either HTML or MHTML file. For Chromium-based browsers (Chrome and Edge) a snapshot by default is taken using CDP command `Page.captureSnapshot`. For other browsers a snapshot is taken using `IWebDriver.PageSource` property.

## Methods

A method added to `Report<TOwner>`:

```cs
public TOwner PageSnapshot(string title = null);
```

Usage:

```cs
Go.To<SomePage>()
    .Report.PageSnapshot();
```

A method added to `AtataContext`:

```cs
public void TakePageSnapshot(string title = null);
```

Usage:

```cs
AtataContext.Current.TakePageSnapshot();
```

## Configuration

A property is added to `AtataContextBuilder`:

```cs
public PageSnapshotsAtataContextBuilder PageSnapshots { get; }
```

`PageSnapshotsAtataContextBuilder` contains the following methods:

```cs
// Used by default.
public PageSnapshotsAtataContextBuilder UseCdpOrPageSourceStrategy();

public PageSnapshotsAtataContextBuilder UsePageSourceStrategy();

public PageSnapshotsAtataContextBuilder UseCdpStrategy();

public PageSnapshotsAtataContextBuilder UseStrategy(IPageSnapshotStrategy strategy);

// The default value is "{snapshot-number:D2} - {snapshot-pageobjectname} {snapshot-pageobjecttypename}{snapshot-title: - *}".
public PageSnapshotsAtataContextBuilder UseFileNameTemplate(string fileNameTemplate);
```

### Usage

```cs
AtataContext.Configure()
    .PageSnapshots.UseCdpStrategy()
    .PageSnapshots.UseFileNameTemplate("{snapshot-number:D2}...");
```

### NUnit

An extra configuration method added to `AtataContextBuilder`:

```cs
public AtataContextBuilder TakePageSnapshotOnNUnitError(string title = "Failed");
```

Also `UseAllNUnitFeatures()` configuration method now includes invoking of `TakePageSnapshotOnNUnitError()`.

## Trigger attribute

Additionally `TakePageSnapshotAttribute` trigger is added.

**Comment by Piedone** [comment]
Can you use this if you don't have a page object? I.e. when visiting a page without using Atata, just navigating to it. We'd take a snapshot of the current page.

**Comment by YevgeniyShunevych** [comment]
You mean you have built `AtataContext` with initialized `Driver`, don't do any `Go.To` navigations, but navigated thru `Driver` directly?

**Comment by Piedone** [comment]
Yes, exactly.

**Comment by YevgeniyShunevych** [comment]
Such scenario was not considered. But I made another commit to make it work. Now it's fine.

**Comment by Piedone** [comment]
Awesome, thank you.! This looks good. We'll check it out once you release it.

**Comment by YevgeniyShunevych** [comment]
Atata v2.4.0 is released already.

**Comment by Piedone** [comment]
Yep, seen it, thanks. We'll check this out as soon as we can.

**Comment by Piedone** [comment]
We've added the usage of this feature to the Lombiq UI Testing Toolbox for Orchard Core in [this PR](https://github.com/Lombiq/UI-Testing-Toolbox/pull/236). In hindsight, it's straightforward, but the first time it was quick complex to understand where the snapshot can actually be retrieved from.

Thank you again!
