### ISSUE TITLE
ControlList.Count.Value is return incorrect number of elements found

### ISSUE THREAD

**Issue by daiphamn** [atata-framework/atata#841]
We have found the first column list in a table by the Xpath below.
```c#
[FindByXPath("//*[@class='tbody']//*[@role='row']/div[1]")]
public ControlList<Text<_>, _> Names { get; private set; }
``` 
When I called Names.Count.Value, I expected it to be 20, but instead I received 500. Each of these contains all the webpage (HTML) text.

**Comment by YevgeniyShunevych** [comment]
`[Find*]` attributes don't work with `ControlList`, they work with `ItemsControl` defining the container control. To specify an XPath for `ControlList` item, you need to use `[ControlDefinition]` attribute like below:

```cs
[ControlDefinition("*[@class='tbody']//*[@role='row']/div[1]")]
public ControlList<Text<_>, _> Names { get; private set; }
```

Please note that preceding `//` should not be added to XPath.

**Comment by daiphamn** [comment]
Thank you. Let me try

**Comment by daiphamn** [comment]
It worked! Thanks

**Comment by YevgeniyShunevych** [comment]
You are welcome.
