### ISSUE TITLE
Screenshot consumers alternative

### ISSUE THREAD

**Issue by gregwinterstein** [atata-framework/atata#845]
We recently updated from Atata v2.14.1 to v3.3.0 and were using `IScreenshotConsumer` implementations to funnel screenshots into our logger implementation. `IScreenshotConsumer` and associated code were removed from Atata in #817.

Are there any alternatives to `IScreenshotConsumer` in v3.3.0 to handle screenshots ourselves?

What was the reasoning behind removing `IScreenshotConsumer`?

**Comment by YevgeniyShunevych** [comment]
Why `IScreenshotConsumer` was removed. After page snapshots functionality was added, we got two similar sub-systems, but they worked and configured absolutely differently. So it was mostly unification and simplifying configuration.

With Atata v3. You can still handle screenshots on your own.

### Set different file path

```cs
 AtataContext.GlobalConfiguration
     .Screenshots.UseFileNameTemplate("...");
```

### Handle event of screenshot taking

There was added `ArtifactAddedEvent` which fires when screenshot/snapshot is made.

```cs
public sealed class CustomScreenshotEventHandler : IEventHandler<ArtifactAddedEvent>
{
    public void Handle(ArtifactAddedEvent eventData, AtataContext context)
    {
        if (eventData.ArtifactType == ArtifactTypes.Screenshot)
        {
            string filePath = eventData.AbsoluteFilePath;
            // TODO: ...
        }
    }
}
```

```cs
 AtataContext.GlobalConfiguration
     .EventSubscriptions.Add(new CustomScreenshotEventHandler())
```

Please let me know whether an approach of handling of screenshots using event handler works for your project.

**Comment by YevgeniyShunevych** [comment]
Thanks for sharing details of your scenario. I'll might rethink returning something similar to `IScreenshotConsumer` later after Atata v4.

**Comment by gregwinterstein** [comment]
For now, handling the events works well enough, to extract the screen shot content.
I don't want to undo your consolidation of the two sub-systems.
